"""SQLAlchemy-statement simulator, NOT a native database or concurrency proof.

Imports production ORM models with registered in-memory Base/security stubs.
No app startup/config/engine/native SQLite is imported or opened. Writer roots
copy state and commit atomically; readers capture one immutable simulated root.
The SQL generated by production code is interpreted here, not replaced by a
mocked repository output. Native MySQL lock behavior remains untested.
"""
import copy
import importlib
import json
import sys
import threading
from types import ModuleType, SimpleNamespace
from sqlalchemy import text
from sqlalchemy.orm import declarative_base
from sqlalchemy.sql.elements import BinaryExpression, BooleanClauseList, BindParameter
from sqlalchemy.sql.dml import Update, Delete
from sqlalchemy.sql.selectable import Select
_loaded = None


def _load():
    global _loaded
    if _loaded is not None:
        sys.modules['app.models.user_account'] = _loaded.account_module
        sys.modules['app.core.database'] = _loaded.database_module
        return _loaded
    database = ModuleType('app.core.database')
    database.Base = declarative_base()
    security = ModuleType('app.core.security')
    security.get_password_hash = lambda v: 'synthetic-hash'
    sys.modules['app.core.database'] = database
    sys.modules['app.core.security'] = security
    account = importlib.import_module('app.models.user_account')
    repository = importlib.import_module('app.repositories.user_models')
    models = importlib.import_module('app.models.user_custom_ai_model')
    inventory = importlib.import_module('app.models.user_model_inventory')
    reservations = importlib.import_module('app.services.byok.reservations')
    _loaded = SimpleNamespace(
        account=account.UserAccount,
        account_module=account,
        database_module=database,
        repo=repository,
        model=models.UserCustomAIModel,
        inventory=inventory.UserModelInventory,
        reservations=reservations
    )
    return _loaded


def _matches(row, clauses):
    for clause in clauses:
        if isinstance(clause, BooleanClauseList):
            if not _matches(row, list(clause.clauses)):
                return False
        elif isinstance(clause, BinaryExpression):
            left = getattr(row, clause.left.key)
            right = clause.right.value if isinstance(
                clause.right,
                BindParameter
            ) else True if str(clause.right) == 'true' else False if str(clause.right) == 'false' else getattr(
                row,
                clause.right.key
            )
            if left != right:
                return False
        else:
            raise AssertionError('unrecognized simulated predicate')
    return True


class Result:

    def __init__(self, rows=(), rowcount=0):
        self.rows = list(rows)
        self.rowcount = rowcount

    def scalar_one_or_none(self):
        assert len(self.rows) <= 1
        return self.rows[0] if self.rows else None

    def scalars(self):
        return self

    def all(self):
        return list(self.rows)


class Session:

    def __init__(self, fixture, read_only=False, after_records=None, failure=None):
        self.f = fixture
        self.read_only = read_only
        self.after_records = after_records
        self.failure = failure
        self.rows = None
        self.active = False
        self.closed = False
        self.committed = False
        self.events = []
        self.locks = []
        self.held = False

    def in_transaction(self):
        return self.active

    def in_nested_transaction(self):
        return False

    def connection(self, execution_options):
        assert not self.active and execution_options == {'isolation_level': 'REPEATABLE READ'}
        self.events.append('isolation:REPEATABLE READ,read_only')
        self.begin()
        return self

    def begin(self):
        assert not self.active
        self.active = True
        self.rows = copy.deepcopy(self.f.rows)
        self.events.append('begin')

    def execute(self, statement):
        assert self.active
        self.f.statements.append(statement)
        if isinstance(statement, type(text('x'))):
            assert str(statement) == 'SET TRANSACTION READ ONLY'
            self.read_only = True
            return Result()
        table = statement.get_final_froms()[0].name if isinstance(
            statement,
            Select
        ) else statement.table.name
        if isinstance(statement, Select) and statement._for_update_arg is not None and (not self.held):
            self.f.writer_lock.acquire()
            self.held = True
            self.rows = copy.deepcopy(self.f.rows)
        rows = self.rows[table]
        if isinstance(statement, Select):
            values = [r for r in rows.values() if _matches(r, statement._where_criteria)]
            if statement._for_update_arg is not None and table not in self.locks:
                self.locks.append(table)
            if table == 'user_custom_ai_models':
                values.sort(key=lambda r: r.id)
            if statement.column_descriptions[0].get('name') == 'id':
                values = [(r.id,) for r in values]
            if table == 'user_custom_ai_models' and self.after_records:
                callback = self.after_records
                self.after_records = None
                callback()
            return Result(values)
        assert not self.read_only
        values = [r for r in rows.values() if _matches(r, statement._where_criteria)]
        if isinstance(statement, Update):
            for row in values:
                for key, value in statement._values.items():
                    setattr(row, key if isinstance(key, str) else key.key, value.value)
        elif isinstance(statement, Delete):
            for row in values:
                del rows[row.id]
        else:
            raise AssertionError('unrecognized simulated statement')
        return Result(rowcount=len(values))

    def add(self, row):
        table = row.__tablename__
        key = row.id if table == 'user_custom_ai_models' else row.user_id
        assert key not in self.rows[table]
        self.rows[table][key] = row

    def flush(self):
        assert self.active

    def commit(self):
        if self.failure == 'commit':
            raise RuntimeError('synthetic commit unknown')
        assert self.active
        self.f.rows = copy.deepcopy(self.rows)
        self.committed = True
        self.active = False

    def rollback(self):
        self.active = False

    def close(self):
        if self.failure == 'close':
            raise RuntimeError('synthetic close unknown')
        self.closed = True
        self.active = False
        if self.held:
            self.f.writer_lock.release()
            self.held = False


class Fixture:

    def __init__(self):
        m = _load()
        self.m = m
        self.model = m.model
        self.rows = {
            'user_accounts': {'synthetic-owner': m.account(username='synthetic-owner', role='student'), 'synthetic-other': m.account(username='synthetic-other', role='teacher')},
            'user_custom_ai_models': {},
            'user_model_inventories': {}
        }
        from app.services.byok.types import AuthenticatedModelActor
        from app.core.byok_crypto import load_byok_keyring
        from app.services.byok.errors import ByokError
        from pydantic import ValidationError
        from app.schemas.user_model import UserCustomModelCreateRequest, UserCustomModelUpdateRequest
        from app.services.byok.limits import WorkCallBudget
        from app.services.byok.schema import compare_schema, BYOK_SCHEMA_CONTRACT
        self.actor = AuthenticatedModelActor.from_current_account(self.rows['user_accounts']['synthetic-owner'])
        self.other = AuthenticatedModelActor.from_current_account(self.rows['user_accounts']['synthetic-other'])
        self.ring = load_byok_keyring(
            'synthetic',
            json.dumps({'synthetic': 'AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8='})
        )
        self.error = ByokError
        self.validation = ValidationError
        self.create = UserCustomModelCreateRequest.model_validate
        self.update = UserCustomModelUpdateRequest.model_validate
        self.caps = WorkCallBudget.student(clock=lambda: 0).reserve('student_chat', 4096)
        self.observation = compare_schema('synthetic-mysql', BYOK_SCHEMA_CONTRACT)
        self.audit = []
        self.statements = []
        self.fingerprint = None
        self.writer_lock = threading.RLock()

    @property
    def configs(self):
        return self.rows['user_custom_ai_models']

    def owner(self, *, failure=None, session=None):
        return self.m.reservations.CustomTransactionOwner(
            lambda: session or Session(self, failure=failure),
            keyring=self.ring,
            schema_observation=self.observation,
            audit=self.audit.append
        )

    def reader(self, after_records=None):
        return self.m.reservations.CustomTransactionOwner(
            lambda: Session(self, True, after_records),
            read_only=True,
            keyring=self.ring,
            schema_observation=self.observation
        )

    def selection(self, id, version):
        from app.schemas.model_selection import CustomSelection
        return CustomSelection(source='custom', config_id=id, config_version=version, model_id='same-id')

    def provenance(self, selection):
        from app.services.byok.types import ModelProvenance
        from app.services.byok.endpoint_policy import normalize_endpoint
        ep = normalize_endpoint('https://provider.example/v1')
        return ModelProvenance(
            selection=selection,
            destination_digest=ep.destination_digest,
            safe_host=ep.host,
            frozen_caps=self.caps
        )

    def seed_evidence(self, id):
        row = self.configs[id]
        self.fingerprint = self.m.repo.configuration_fingerprint(row)
        row.capability_evidence = [{
            'config_version': row.config_version,
            'origin_config_version': row.config_version,
            'adapter_id': 'openai_chat_completions_v1',
            'adapter_version': '1',
            'policy_version': 'work-byok@1',
            'model_id': 'same-id',
            'probe_kind': 'text',
            'generation': 1,
            'checked_at': '2026-10-07T00:00:00Z',
            'duration_ms': 1,
            'evidence_id': 'synthetic-evidence',
            'configuration_fingerprint': self.fingerprint
        }]
        self.rows['user_model_inventories']['synthetic-owner'].inventory_revision += 1

    def state(self):
        return json.dumps(
            {t: {k: {a: v for a, v in vars(r).items() if a != '_sa_instance_state'} for k, r in rows.items()} for t, rows in self.rows.items()},
            sort_keys=True
        )

    def change_role(self, role):
        self.rows['user_accounts']['synthetic-owner'].role = role

    def delete_account(self):
        del self.rows['user_accounts']['synthetic-owner']
        self.configs.clear()
        self.rows['user_model_inventories'].pop('synthetic-owner', None)

    def recreate_account(self):
        self.rows['user_accounts']['synthetic-owner'] = self.m.account(
            username='synthetic-owner',
            role='student'
        )

    def seed_orphan(self, id):
        self.configs[id] = self.model(
            id=id,
            user_id='synthetic-owner',
            name='Legacy',
            provider='Legacy',
            adapter_id=None,
            base_url='https://provider.example/v1',
            encrypted_api_key='SYNTHETIC-LEGACY-NEVER-DECRYPT',
            credential_envelope=None,
            owner_binding_token=None,
            credential_state='legacy_reentry_required',
            config_version=1,
            credential_version=0,
            consent_version=0,
            destination_digest=None,
            model_ids=['same-id'],
            response_model_aliases={},
            capability_evidence=[],
            probe_generations={},
            is_active=False
        )

    def invocation_snapshot(self, value):
        return self.m.reservations.consume_committed_snapshot(value)


def fixture():
    return Fixture()
