// Shipped Vue 3.3.4 runtime + its own compiler/custom renderer. No SSR/browser/main/server.
import test from 'node:test';
import assert from 'node:assert/strict';
import * as Vue from '../libs/vue.esm-browser.js';
import { registerHooks } from 'node:module';
import { readFileSync } from 'node:fs';
const sourceRoot=new URL('../js/',import.meta.url).href,vueURL=new URL('../libs/vue.esm-browser.js',import.meta.url).href;
// Same bounded importmap mapping as the existing selector/foreground compatibility tests.
registerHooks({resolve(specifier,context,nextResolve){const resolved=nextResolve(specifier,context);return specifier==='vue'&&context.parentURL?.startsWith(sourceRoot)?{url:vueURL,shortCircuit:true}:resolved;}});
const {default:Dashboard}=await import('../js/components/StudentDashboard.js');
const {useStudentNavigationPresentation}=await import('../js/hooks/useStudentNavigationPresentation.js');
const {getTeachingMenuInfo}=await import('../js/controllers/teachingNavigation.js');
assert.equal(Vue.version,'3.3.4');
globalThis.fetch=()=>{throw Error('Unregistered network work');};
const source=path=>readFileSync(new URL('../'+path,import.meta.url),'utf8');
const walk=el=>[el,...el.children.flatMap(walk)],textOf=el=>el.tag==='#comment'?'':el.text+el.children.map(textOf).join('');
function node(tag='',text=''){return{tag,text,props:{},children:[],parent:null};}
const renderer=Vue.createRenderer({createElement:tag=>node(tag),createText:text=>node('#text',text),createComment:text=>node('#comment',text),setText:(el,text)=>el.text=text,setElementText:(el,text)=>{el.text=text;el.children=[];},parentNode:el=>el.parent,nextSibling:el=>el.parent?.children[el.parent.children.indexOf(el)+1]||null,insert(el,parent,anchor){if(el.parent){const i=el.parent.children.indexOf(el);if(i>=0)el.parent.children.splice(i,1);}el.parent=parent;const i=anchor?parent.children.indexOf(anchor):-1;if(i<0)parent.children.push(el);else parent.children.splice(i,0,el);},remove(el){if(el.parent){const i=el.parent.children.indexOf(el);if(i>=0)el.parent.children.splice(i,1);el.parent=null;}},patchProp(el,key,_old,value){el.props[key]=value;}});
const compiled=C=>({...C,render:Vue.compile(C.template,{hoistStatic:false,decodeEntities(raw){assert.doesNotMatch(raw,/&(?:#\d+|#x[\da-f]+|[a-z]+);/iu,'No entity decoding substitution');return raw;}})});
const settle=async()=>{await Vue.nextTick();await new Promise(resolve=>setImmediate(resolve));await Vue.nextTick();};
const button=(root,label)=>walk(root).find(el=>el.tag==='button'&&textOf(el).trim()===label);
async function mount(component,props={}){const root=node('root'),errors=[],warnings=[],emitted={};let vm;const C=compiled(component),handlers=Object.fromEntries((C.emits||[]).map(event=>['on'+event[0].toUpperCase()+event.slice(1),(...args)=>(emitted[event]??=[]).push(args)]));const app=renderer.createApp({render:()=>Vue.h(C,{...props,...handlers,ref:value=>vm=value})});app.config.errorHandler=e=>errors.push(e);app.config.warnHandler=e=>warnings.push(e);app.mount(root);await settle();return{root,get vm(){return vm;},emitted,close(){app.unmount();assert.deepEqual(errors,[]);assert.deepEqual(warnings,[]);}};}
test('shipped 3.3.4 compiler renders real list counts completed exam notifications and bounded actions',async()=>{
 const h=await mount(Dashboard,{homeworkList:[{id:'P',title:'真实待交',subject:'课程',submitted:false},{id:'S',title:'真实已交',submitted:true}],examAlerts:[{id:'E',name:'已结束真实考试',status:'completed'}],errorNotebook:[{id:'M',question:'真实错题',mastered:false}]});try{assert.equal(Vue.version,'3.3.4');assert.equal(h.vm.pendingCount,1);assert.equal(h.vm.submittedCount,1);assert.equal(h.vm.examCount,1);assert.match(textOf(h.root),/已结束|待巩固/);for(const [label,destination] of [['查看作业','homework'],['查看考试','exam'],['去复习','mistakes'],['进入当前任务','teaching-home'],['打开一站式 Work','workspace']]){button(h.root,label).props.onClick();assert.deepEqual(h.emitted.navigate.at(-1),[destination]);}button(h.root,'刷新').props.onClick();assert.deepEqual(h.emitted.refresh,[[]]);assert.deepEqual(Object.keys(h.emitted).sort(),['navigate','refresh']);}finally{h.close();}
});
test('shipped 3.3.4 native tab handlers filter facts and move keyboard focus without source mutation',async()=>{
 const rows=[{id:'P',title:'真实待交',submitted:false},{id:'S',title:'真实已交',submitted:true}],before=JSON.stringify(rows),h=await mount(Dashboard,{homeworkList:rows});try{let focuses=0;const tabs=walk(h.root).filter(el=>el.props.role==='tab');for(const el of tabs)el.focus=()=>focuses++;const event=new Event('keydown',{cancelable:true});Object.defineProperties(event,{key:{value:'ArrowRight'},currentTarget:{value:{parentElement:{querySelectorAll:()=>tabs}}}});await tabs[0].props.onKeydown(event);await settle();assert.equal(event.defaultPrevented,true);assert.equal(h.vm.activeTab,'submitted');assert.match(textOf(h.root),/真实已交/);assert.doesNotMatch(textOf(h.root),/真实待交/);assert.equal(focuses,1);assert.equal(JSON.stringify(rows),before);}finally{h.close();}
});
test('shipped 3.3.4 loading errors and successful empty states remain distinct',async()=>{
 for(const props of [{loading:true},{error:'raw-error'},{ }]){const h=await mount(Dashboard,props);try{if(props.loading||props.error){assert.equal(h.vm.summaryAvailable,false);assert.equal(walk(h.root).filter(el=>el.props['data-summary-value']&&textOf(el)==='0').length,0);assert.doesNotMatch(textOf(h.root),/暂无待提交/);}else{assert.equal(h.vm.summaryAvailable,true);assert.match(textOf(h.root),/暂无待提交作业|暂无考试通知|暂无近期错题/);}if(props.error)assert.doesNotMatch(textOf(h.root),/raw-error/);}finally{h.close();}}
});
test('shipped 3.3.4 long API text renders as text and unknown states stay unspecified',async()=>{
 const text='长标题'.repeat(70)+' <script>inert</script>',h=await mount(Dashboard,{homeworkList:[{id:'H',title:text}],examAlerts:[{id:'E',name:text,status:'unknown'}],errorNotebook:[{id:'M',question:text}]});try{assert.ok(textOf(h.root).includes(text));assert.equal(walk(h.root).some(el=>el.tag==='script'),false);assert.match(textOf(h.root),/未提供|状态未提供/);assert.doesNotMatch(textOf(h.root),/待参加|未掌握/);}finally{h.close();}
});
test('shipped 3.3.4 compiled rail uses actual focus hover scroll Escape handlers without legacy active classes',async()=>{
 const html=source('index.html'),start=html.indexOf('<nav id="legacy-global-navigation"'),end=html.indexOf('</nav>',start)+6,auth=source('js/hooks/useAuth.js'),literal=auth.slice(auth.indexOf('const studentMenus = ['),auth.indexOf('const teacherMenus = ['));
 const entries=[...literal.matchAll(/\{ id: '([^']+)', name: '([^']+)', icon: '([^']+)'/g)].map(([,id,name,icon])=>({id,name,icon}));let navigation;const role=Vue.ref('student'),view=Vue.ref('dashboard'),routes=[];
 const h=await mount({template:html.slice(start,end),setup(){navigation=useStudentNavigationPresentation(role);return{...navigation,currentRole:role,currentUser:{username:'synthetic'},thinkingAgent:null,activeMenus:[getTeachingMenuInfo('teaching-home'),...entries],currentView:Vue.computed({get:()=>view.value,set:value=>routes.push(value)}),openUserCenter(){},handleLogout(){}};}});
 try{const controls=walk(h.root).filter(el=>el.tag==='button'&&el.props.class?.includes('ios-menu-btn'));assert.equal(controls.length,13);assert.doesNotMatch(controls.find(el=>el.props['aria-current']==='page').props.class,/ios-menu-btn-active-student|shadow-md/);const collapse=walk(h.root).find(el=>el.props['aria-controls']==='legacy-global-navigation');collapse.props.onClick();await settle();assert.equal(collapse.props['aria-expanded'],false);let top=100;const a={currentTarget:{getBoundingClientRect:()=>({top,height:40})}},b={currentTarget:{getBoundingClientRect:()=>({top:300,height:40})}};controls[0].props.onFocus(a);controls[1].props.onMouseenter(b);controls[1].props.onMouseleave(b);assert.equal(navigation.studentNavHoverLabel.value.label,controls[0].props['aria-label']);top=180;walk(h.root).find(el=>el.props.class?.includes('student-nav-items')).props.onScroll();assert.equal(navigation.studentNavHoverLabel.value.top,200);const escape=new Event('keydown',{cancelable:true});Object.defineProperty(escape,'key',{value:'Escape'});walk(h.root).find(el=>el.tag==='nav').props.onKeydown(escape);assert.equal(escape.defaultPrevented,true);assert.equal(navigation.studentNavHoverLabel.value,null);controls[1].props.onClick();assert.equal(routes.at(-1),entries[0].id);assert.equal(view.value,'dashboard');collapse.props.onClick();await settle();assert.equal(navigation.studentNavHoverLabel.value,null);}finally{h.close();}
});
