// Source-pinned synthetic read tests. Official Vue compiler/renderer/SSR only;
// no DOM, application entry, browser, backend, or live API execution.
import test from 'node:test';
import assert from 'node:assert/strict';
import * as Vue from 'vue';
import { compile } from '@vue/compiler-dom';
import { renderToString } from '@vue/server-renderer';
import { fixtures as f, clone, deferred, at } from './fixtures/teachingAssessmentFixtures.mjs';
import { readFileSync } from 'node:fs';
const modules={};
for(const [key,path] of Object.entries({access:'../js/utils/teachingReadAccess.js',hook:'../js/hooks/useTeachingAssignments.js',time:'../js/utils/teachingTime.js',workspace:'../js/components/teaching/TeachingAssignmentReadWorkspace.js'})){
 try{modules[key]=await import(path);}catch(error){if(error.code!=='ERR_MODULE_NOT_FOUND')throw error;}
}
const requireFeature=()=>{assert.equal(typeof modules.access?.teachingReadAccess,'function','A pure current-context teachingReadAccess model must exist');assert.equal(typeof modules.hook?.useTeachingAssignments,'function','Fenced B2 mounted read owner must exist');};
const ctx=(extra={})=>({authVerified:true,authEpoch:1,contextEpoch:7,actorId:'student-A',currentRole:'student',offeringId:'offering-A',courseId:'course-A',roleScope:'offering',configuredPermissions:['AUTHOR','RELEASE'],projection:'current-server-projection',mode:'teaching',modes:['teaching'],b1:{readReady:true},assignments:{readReady:true,reason:'write_safety_unproven'},mutationAllowed:false,...extra});
const apiFactory=(overrides={})=>({listAssignments:async()=>clone(f.assignmentPage),getDraft:async()=>clone(f.draft),listVersions:async()=>clone(f.versionPage),getVersion:async()=>clone(f.version),listReleases:async()=>clone(f.releasePage),getRelease:async()=>clone(f.release),...overrides});
function owner({context=ctx(),active=true,api=apiFactory()}={}){requireFeature();const c=Vue.ref(context),a=Vue.ref(active),scope=Vue.effectScope();let h;scope.run(()=>h=modules.hook.useTeachingAssignments({context:c,active:a,api}));return{h,c,a,close:()=>scope.stop()};}
const settle=async()=>{await Vue.nextTick();await new Promise(resolve=>setImmediate(resolve));await Vue.nextTick();};
function node(tag='',text=''){return{tag,text,props:{},children:[],parent:null};}
const renderer=Vue.createRenderer({createElement:tag=>node(tag),createText:text=>node('#text',text),createComment:text=>node('#comment',text),setText:(el,text)=>el.text=text,setElementText:(el,text)=>{el.text=text;el.children=[];},parentNode:el=>el.parent,nextSibling:el=>el.parent?.children[el.parent.children.indexOf(el)+1]||null,insert(el,parent,anchor){if(el.parent)el.parent.children.splice(el.parent.children.indexOf(el),1);el.parent=parent;const i=anchor?parent.children.indexOf(anchor):-1;if(i<0)parent.children.push(el);else parent.children.splice(i,0,el);},remove(el){if(el.parent)el.parent.children.splice(el.parent.children.indexOf(el),1);el.parent=null;},patchProp:(el,key,_old,value)=>el.props[key]=value});
const walk=el=>[el,...el.children.flatMap(walk)],textOf=el=>el.tag==='#comment'?'':el.text+el.children.map(textOf).join('');
function compiled(C){assert.ok(C,'Actual read component must exist');return{...C,components:Object.fromEntries(Object.entries(C.components||{}).map(([key,value])=>[key,compiled(value)])),render:Object.assign(new Function('Vue',compile(C.template,{mode:'function'}).code)(Vue),{_rc:true})};}
async function mount(props){const C=compiled(modules.workspace?.default),root=node('root'),errors=[],warnings=[];const app=renderer.createApp({render:()=>Vue.h(C,props)});app.config.errorHandler=e=>errors.push(e);app.config.warnHandler=e=>warnings.push(e);app.mount(root);await settle();return{root,ssr:()=>renderToString(Vue.createSSRApp(C,props)),close(){app.unmount();assert.deepEqual(errors,[]);assert.deepEqual(warnings,[]);}};}

test('current local model separates AUTHOR RELEASE SUBMISSION_VIEW and never grants by global role',()=>{requireFeature();const access=modules.access.teachingReadAccess;
 const author=access(ctx({configuredPermissions:['AUTHOR']}));assert.equal(author.canReadCatalog,true);assert.equal(author.canReadDraft,true);assert.equal(author.canReadVersions,true);assert.equal(author.canReadReleases,false);assert.equal(author.catalogProjection,'author_draft');
 const release=access(ctx({configuredPermissions:['RELEASE']}));assert.equal(release.canReadDraft,false);assert.equal(release.catalogProjection,'release_frozen');assert.equal(release.canReadReleases,true);
 const submission=access(ctx({configuredPermissions:['SUBMISSION_VIEW']}));assert.equal(submission.canReadCatalog,false);assert.equal(submission.canReadVersions,false);assert.equal(submission.canReadReleases,true);assert.equal(submission.canReadTeacherSubmissions,true);
 assert.equal(access(ctx({currentRole:'teacher',configuredPermissions:[]})).canReadCatalog,false);assert.equal(access(ctx({mutationAllowed:true})).mutationAllowed,false);
});
test('entry requires verified epochs fresh selected offering both ready stages and explicit current mode',()=>{requireFeature();for(const extra of [{authVerified:false},{authEpoch:null},{contextEpoch:null},{actorId:null},{offeringId:null},{b1:{readReady:false}},{assignments:{readReady:false}},{mode:null,modes:['teaching','learning']},{mode:'teaching',modes:['learning']},{projection:null},{roleScope:'assigned',mode:'learning',modes:['teaching','learning']}]){const a=modules.access.teachingReadAccess(ctx(extra));assert.equal(a.ready,false,JSON.stringify(extra));assert.equal(a.canReadReleases,false);}});
test('learning model exposes release own entry only and ignores teacher permissions',()=>{requireFeature();const a=modules.access.teachingReadAccess(ctx({mode:'learning',modes:['learning'],roleScope:null,configuredPermissions:['AUTHOR','RELEASE','SUBMISSION_VIEW']}));assert.equal(a.canReadReleases,true);assert.equal(a.canReadOwnSubmissions,true);assert.equal(a.canReadCatalog,false);assert.equal(a.canReadDraft,false);assert.equal(a.canReadVersions,false);assert.equal(a.canReadTeacherSubmissions,false);});
test('inactive or unavailable view sends no B2 GET and no speculative read runs at hook creation',async()=>{let reads=0;const api=apiFactory(Object.fromEntries(['listAssignments','getDraft','listVersions','getVersion','listReleases','getRelease'].map(k=>[k,async()=>{reads++;throw Error('unexpected');}])));for(const options of [{active:false},{context:ctx({assignments:{readReady:false}})},{context:ctx({roleScope:'assigned'})}]){const o=owner({...options,api});try{await o.h.refresh();assert.equal(reads,0);assert.equal(o.h.selection.assignmentId,null);}finally{o.close();}}});
test('teacher catalog draft versions and release details preserve actual offering assignment version ancestry',async()=>{const o=owner();try{assert.equal(await o.h.loadAssignments(),true);assert.equal(await o.h.selectAssignment('assignment-A'),true);assert.equal(o.h.draft.data.public_spec.title,f.spec.title);assert.equal(o.h.versionPage.items.length,1);assert.equal(await o.h.selectVersion('version-A'),true);assert.equal(o.h.version.data.id,'version-A');assert.equal(await o.h.loadReleases(),true);assert.equal(await o.h.selectRelease('release-A'),true);assert.equal(o.h.release.data.version.offering_id,'offering-A');assert.equal(o.h.selection.assignmentId,null);assert.equal(o.h.draft.data,null);}finally{o.close();}});
test('RELEASE only opens latest frozen public version and never reads public draft',async()=>{let drafts=0;const o=owner({context:ctx({configuredPermissions:['RELEASE']}),api:apiFactory({listAssignments:async()=>clone(f.frozenAssignmentPage),getDraft:async()=>{drafts++;throw Error('forbidden');}})});try{await o.h.loadAssignments();assert.equal(await o.h.selectAssignment('assignment-A'),true);assert.equal(o.h.version.data.id,'version-A');assert.equal(o.h.draft.data,null);assert.equal(drafts,0);}finally{o.close();}});
test('learning filters management before installation and reads public frozen version only from accepted own release',async()=>{let forbidden=0;const o=owner({context:ctx({mode:'learning',modes:['learning'],roleScope:null}),api:apiFactory({listAssignments:async()=>{forbidden++;},getDraft:async()=>{forbidden++;},listVersions:async()=>{forbidden++;},getVersion:async()=>{forbidden++;},getRelease:async id=>clone(id==='release-A'?f.release:f.management)})});try{await o.h.refresh();assert.deepEqual(o.h.releasePage.items.map(x=>x.id),['release-A']);assert.equal(o.h.releasePage.loadedCount,1);assert.equal(JSON.stringify(o.h.releasePage).includes('recipient_count'),false);assert.equal(await o.h.selectRelease('release-B'),false);assert.equal(await o.h.selectRelease('release-A'),true);assert.equal(o.h.release.data.version.public_spec.title,f.spec.title);assert.equal(forbidden,0);}finally{o.close();}});
test('learning all-filtered first page keeps opaque cursor and load-more without fabricated all-own count',async()=>{let n=0;const o=owner({context:ctx({mode:'learning',modes:['learning'],roleScope:null}),api:apiFactory({listReleases:async()=>++n===1?{items:[clone(f.management)],next_cursor:'AAAA',as_of:at}:{items:[clone(f.release)],next_cursor:null,as_of:at}})});try{await o.h.loadReleases();assert.equal(o.h.releasePage.items.length,0);assert.equal(o.h.releasePage.nextCursor,'AAAA');assert.equal(o.h.releasePage.status,'ready');assert.equal(await o.h.loadMore('releasePage'),true);assert.equal(o.h.releasePage.loadedCount,1);assert.deepEqual(o.h.releasePage.items.map(x=>x.id),['release-A']);}finally{o.close();}});
test('learning detail rejects newly returned management projection and clears accepted list and content',async()=>{const o=owner({context:ctx({mode:'learning',modes:['learning'],roleScope:null}),api:apiFactory({getRelease:async()=>clone(f.management)})});try{await o.h.loadReleases();assert.equal(await o.h.selectRelease('release-A'),false);assert.equal(o.h.release.data,null);assert.equal(o.h.releasePage.items.length,0);assert.equal(o.h.release.status,'unavailable');}finally{o.close();}});
test('old success error and finally cannot install content or finish newer current request',async()=>{for(const oldFailure of [false,true]){const old=deferred(),newer=deferred();let reads=0;const o=owner({api:apiFactory({listAssignments:()=>++reads===1?old.promise:newer.promise})});try{const a=o.h.loadAssignments();o.c.value=ctx({contextEpoch:8});const b=o.h.loadAssignments();if(oldFailure)old.reject({status:403,reason:'permission_denied'});else old.resolve(clone(f.assignmentPage));await a;assert.equal(o.h.assignmentPage.status,'loading');assert.equal(o.h.assignmentPage.items.length,0);newer.resolve(clone(f.assignmentPage));assert.equal(await b,true);assert.equal(o.h.assignmentPage.status,'ready');}finally{o.close();}}});
test('auth context actor offering mode projection readiness and inactive changes synchronously erase descendants',async()=>{for(const extra of [{authEpoch:2},{contextEpoch:8},{actorId:'other'},{offeringId:'other'},{mode:'learning',modes:['learning'],roleScope:null},{projection:'new'},{configuredPermissions:['RELEASE']},{assignments:{readReady:false}},{authVerified:false}]){const o=owner();try{await o.h.loadAssignments();await o.h.selectAssignment('assignment-A');o.c.value=ctx(extra);assert.equal(o.h.assignmentPage.items.length,0);assert.equal(o.h.draft.data,null);assert.equal(o.h.selection.assignmentId,null);}finally{o.close();}}const o=owner();try{await o.h.loadAssignments();o.a.value=false;assert.equal(o.h.assignmentPage.items.length,0);}finally{o.close();}});
test('invalid newer selection and cursor fence pending reply before validation error',async()=>{for(const kind of ['selection','cursor']){const pending=deferred();const o=owner({api:apiFactory(kind==='selection'?{getDraft:()=>pending.promise}:{listAssignments:()=>pending.promise})});try{let work;if(kind==='selection'){await o.h.loadAssignments();work=o.h.selectAssignment('assignment-A');await o.h.selectAssignment('foreign');}else{work=o.h.loadAssignments();await o.h.loadAssignments({cursor:'AAAA'});}pending.resolve(clone(kind==='selection'?f.draft:f.assignmentPage));await work;assert.equal(kind==='selection'?o.h.draft.data:o.h.assignmentPage.items.length,kind==='selection'?null:0);assert.equal(kind==='selection'?o.h.draft.status:o.h.assignmentPage.status,'error');}finally{o.close();}}});
test('current 401 403 404 denial including next page clears all stale names public body and cursors',async()=>{for(const status of [401,403,404]){let n=0;const o=owner({api:apiFactory({listAssignments:async()=>++n===1?{...clone(f.assignmentPage),next_cursor:'AAAA'}:Promise.reject({status,reason:status===401?'unauthenticated':status===404?'not_found':'permission_denied',message:'SECRET'})})});try{await o.h.loadAssignments();await o.h.selectAssignment('assignment-A');assert.equal(await o.h.loadMore('assignmentPage'),false);assert.equal(o.h.assignmentPage.items.length,0);assert.equal(o.h.assignmentPage.nextCursor,null);assert.equal(o.h.draft.data,null);assert.equal(o.h.selection.assignmentId,null);assert.equal(o.h.assignmentPage.status,'unavailable');assert.equal(JSON.stringify([o.h.assignmentPage,o.h.draft,o.h.release,o.h.selection]).includes('SECRET'),false);}finally{o.close();}}});
test('non-auth page failure retains accepted same-authority rows as explicitly stale partial data',async()=>{let n=0;const o=owner({api:apiFactory({listAssignments:async()=>++n===1?{...clone(f.assignmentPage),next_cursor:'AAAA'}:Promise.reject({status:503,reason:'database_unavailable'})})});try{await o.h.loadAssignments();await o.h.loadMore('assignmentPage');assert.equal(o.h.assignmentPage.items.length,1);assert.equal(o.h.assignmentPage.partial,true);assert.equal(o.h.assignmentPage.status,'error');assert.equal(await o.h.selectAssignment('assignment-A'),false);}finally{o.close();}});
test('catalog projection mismatch and draft offering mismatch fail closed as invalid responses',async()=>{for(const overrides of [{listAssignments:async()=>clone(f.frozenAssignmentPage)},{getDraft:async()=>({...clone(f.draft),offering_id:'other'})}]){const o=owner({api:apiFactory(overrides)});try{await o.h.loadAssignments();await o.h.selectAssignment('assignment-A');assert.equal(o.h.draft.data,null);assert.equal(o.h.assignmentPage.items.length>0,o.h.assignmentPage.status==='ready');assert.equal(o.h.draft.status==='error'||o.h.assignmentPage.status==='error',true);}finally{o.close();}}});
test('versions require installed parent assignment and detail requires installed exact version row',async()=>{const o=owner();try{assert.equal(await o.h.loadVersions('assignment-A'),false);await o.h.loadAssignments();await o.h.selectAssignment('assignment-A');assert.equal(await o.h.selectVersion('foreign'),false);assert.equal(o.h.version.data,null);}finally{o.close();}});
test('release detail cannot change installed assignment version or offering ancestry',async()=>{for(const field of ['assignment','version','offering']){const data=clone(f.release);if(field==='assignment'){data.assignment_id='other';data.version.assignment_id='other';}if(field==='version')data.version.id='other';if(field==='offering')data.version.offering_id='other';const o=owner({api:apiFactory({getRelease:async()=>data})});try{await o.h.loadReleases();assert.equal(await o.h.selectRelease('release-A'),false);assert.equal(o.h.release.data,null);assert.equal(o.h.release.status,'error');}finally{o.close();}}});
test('duplicate pages cursor cycles and changed limits cannot append or revive old selection',async()=>{for(const variant of ['duplicate','cycle','query']){let n=0;const o=owner({api:apiFactory({listAssignments:async()=>++n===1?{...clone(f.assignmentPage),next_cursor:'AAAA'}:{items:variant==='duplicate'?[clone(f.author)]:[{...clone(f.author),id:'assignment-B'}],next_cursor:variant==='cycle'?'AAAA':null,as_of:at}})});try{await o.h.loadAssignments();const result=await o.h.loadAssignments({cursor:'AAAA',limit:variant==='query'?10:50});assert.equal(result,false);assert.equal(o.h.assignmentPage.status,'error');}finally{o.close();}}});
test('unmount aborts pending detail and watcher with no late content or loading',async()=>{const pending=deferred();let signal;const o=owner({api:apiFactory({getDraft:(_id,options)=>{signal=options.signal;return pending.promise;}})});await o.h.loadAssignments();const work=o.h.selectAssignment('assignment-A');o.close();assert.equal(signal.aborted,true);pending.resolve(clone(f.draft));assert.equal(await work,false);assert.equal(o.h.draft.data,null);assert.equal(o.h.draft.status,'idle');});
test('UTC display uses release snapshot timezone without changing wire microseconds or spec',()=>{requireFeature();assert.equal(typeof modules.time?.formatTeachingTime,'function');const result=modules.time.formatTeachingTime(at,'Asia/Shanghai');assert.match(result,/2026|Asia\/Shanghai/);assert.match(result,/12:30:00/);assert.match(result,/123456/);assert.equal(modules.time.formatTeachingTime('invalid','UTC'),'时间不可用');assert.equal(at,'2026-10-04T04:30:00.123456Z');});
test('actual workspace renders inert draft immutable version and teacher own public release without invented count',async()=>{const o=owner();try{await o.h.loadAssignments();await o.h.selectAssignment('assignment-A');let mounted=await mount({workspace:o.h});try{assert.match(textOf(mounted.root),/草稿|固定版本|已发布任务|第一行/);assert.ok((await mounted.ssr()).includes('&lt;script&gt;inert&lt;/script&gt;'));assert.equal(walk(mounted.root).filter(x=>x.tag==='script'||x.tag==='textarea').length,0);}finally{mounted.close();}await o.h.loadReleases();await o.h.selectRelease('release-A');mounted=await mount({workspace:o.h});try{assert.match(textOf(mounted.root),/固定版本|AI|无截止时间/);assert.doesNotMatch(textOf(mounted.root),/接收人数|0 人|待批改|发布作业|提交作业/);}finally{mounted.close();}}finally{o.close();}});
test('workspace native selection pagination refresh empty error and loading controls invoke bounded reads',async()=>{let reads=0;const o=owner({api:apiFactory({listAssignments:async()=>{reads++;return{...clone(f.assignmentPage),next_cursor:'AAAA'};}})});try{await o.h.loadAssignments();const mounted=await mount({workspace:o.h});try{const buttons=()=>walk(mounted.root).filter(x=>x.tag==='button');const open=buttons().find(x=>textOf(x)==='打开草稿');assert.equal(open.props.type,'button');await open.props.onClick();await settle();assert.equal(o.h.selection.assignmentId,'assignment-A');assert.ok(buttons().some(x=>textOf(x)==='继续读取作业'));const refresh=buttons().find(x=>textOf(x)==='重新读取任务');await refresh.props.onClick();assert.ok(reads>1);}finally{mounted.close();}}finally{o.close();}});
test('workspace does not expose stale resources if current access or projection becomes unavailable',async()=>{const o=owner();try{await o.h.loadAssignments();await o.h.selectAssignment('assignment-A');const mounted=await mount({workspace:o.h});try{o.c.value=ctx({authVerified:false});await settle();assert.doesNotMatch(textOf(mounted.root),/公开任务|第一行|接收人数/);}finally{mounted.close();}}finally{o.close();}});
test('mounted seam wires tasks only preserves truthful unconnected history and main is never imported',()=>{const main=readFileSync(new URL('../js/main.js',import.meta.url),'utf8'),html=readFileSync(new URL('../index.html',import.meta.url),'utf8'),shell=readFileSync(new URL('../js/components/teaching/TeachingWorkbenchShell.js',import.meta.url),'utf8');assert.match(main,/teachingAssignments: teachingWorkbench\.assignments/);assert.match(html,/:assignments="teachingAssignments"/);assert.match(shell,/section === 'tasks'/);assert.match(shell,/TeachingAssignmentReadWorkspace/);assert.match(shell,/提交记录.*读取界面尚未接入/);});

test('new selected detail does not display previous draft body while version is loading or denied',async()=>{const waiting=deferred();const o=owner({api:apiFactory({getVersion:()=>waiting.promise})});try{await o.h.loadAssignments();await o.h.selectAssignment('assignment-A');const mounted=await mount({workspace:o.h});try{const read=o.h.selectVersion('version-A');await settle();assert.match(textOf(mounted.root),/正在读取/);assert.doesNotMatch(textOf(mounted.root),/第一行/);waiting.reject({status:404,reason:'not_found'});await read;await settle();assert.doesNotMatch(textOf(mounted.root),/第一行|公开任务/);assert.match(textOf(mounted.root),/不存在或当前不可访问/);}finally{mounted.close();}}finally{o.close();}});
test('invalid detail selection presents a real sanitized error and refresh control instead of hidden failure',async()=>{const o=owner();try{await o.h.loadReleases();await o.h.selectRelease('foreign');const mounted=await mount({workspace:o.h});try{assert.match(textOf(mounted.root),/读取失败/);assert.doesNotMatch(textOf(mounted.root),/不存在的标题/);assert.ok(walk(mounted.root).some(x=>x.tag==='button'&&textOf(x)==='重新读取任务'));}finally{mounted.close();}}finally{o.close();}});
test('RELEASE catalog opens latest frozen version beyond first accepted version page through its bound cursor',async()=>{const latest={...clone(f.versionSummary),id:'version-B',version_number:2},catalog={items:[{...clone(f.frozen),latest_version_id:'version-B',latest_version_number:2}],next_cursor:null,as_of:at};let pages=0;const o=owner({context:ctx({configuredPermissions:['RELEASE']}),api:apiFactory({listAssignments:async()=>catalog,listVersions:async(_id,query)=>{pages++;return query.cursor?{items:[latest],next_cursor:null,as_of:at}:{items:[clone(f.versionSummary)],next_cursor:'AAAA',as_of:at};},getVersion:async(_a,id)=>({...clone(f.version),id,version_number:2})})});try{await o.h.loadAssignments();assert.equal(await o.h.selectAssignment('assignment-A'),true);assert.equal(o.h.version.data.id,'version-B');assert.equal(pages,2);}finally{o.close();}});
test('invalid newer version-page cursor clears selected frozen detail and cancels old pending append',async()=>{const pending=deferred();let pages=0;const o=owner({api:apiFactory({listVersions:async()=>++pages===1?{...clone(f.versionPage),next_cursor:'AAAA'}:pending.promise})});try{await o.h.loadAssignments();await o.h.selectAssignment('assignment-A');await o.h.selectVersion('version-A');const work=o.h.loadMore('versionPage');await o.h.loadVersions('assignment-A',{cursor:'BBBB'});assert.equal(o.h.version.data,null);assert.equal(o.h.selection.versionId,null);pending.resolve({items:[],next_cursor:null,as_of:at});assert.equal(await work,false);assert.equal(o.h.version.data,null);}finally{o.close();}});
test('release fixed-version public body must match installed immutable snapshot even with identical locator and hash',async()=>{const changed=clone(f.release);changed.version.public_spec.instructions='CHANGED_BODY';const o=owner({api:apiFactory({getRelease:async()=>changed})});try{await o.h.loadReleases();assert.equal(await o.h.selectRelease('release-A'),false);assert.equal(o.h.release.data,null);assert.equal(o.h.release.error.reason,'invalid_response');}finally{o.close();}});
test('public release unknown or hidden count never becomes a fabricated count in learning SSR',async()=>{const o=owner({context:ctx({mode:'learning',modes:['learning'],roleScope:null})});try{await o.h.refresh();await o.h.selectRelease('release-A');const mounted=await mount({workspace:o.h});try{const text=await mounted.ssr();assert.match(text,/已加载可见记录 1 条/);assert.doesNotMatch(text,/接收人数|recipient_count|recipient_digest|全部作业|共 2/);}finally{mounted.close();}}finally{o.close();}});
test('invalid newer assignment or release selection cancels pending parent-page response and loading cleanup',async()=>{for(const kind of ['assignmentPage','releasePage']){const pending=deferred();let signal;const api=apiFactory({[kind==='assignmentPage'?'listAssignments':'listReleases']:(_id,options)=>{signal=options.signal;return pending.promise;}});const o=owner({api});try{const work=kind==='assignmentPage'?o.h.loadAssignments():o.h.loadReleases();await(kind==='assignmentPage'?o.h.selectAssignment('foreign'):o.h.selectRelease('foreign'));assert.equal(signal.aborted,true);pending.resolve(clone(kind==='assignmentPage'?f.assignmentPage:f.releasePage));assert.equal(await work,false);assert.equal(o.h[kind].items.length,0);assert.notEqual(o.h[kind].status,'loading');}finally{o.close();}}});
test('visible filter changes are native local input only and list content remains inert text',async()=>{const o=owner();try{await o.h.loadAssignments();const mounted=await mount({workspace:o.h});try{const input=walk(mounted.root).find(x=>x.tag==='input');assert.equal(input.props.type,'search');input.props.onInput({target:{value:'absent'}});await settle();assert.match(textOf(mounted.root),/没有匹配标题/);assert.equal(walk(mounted.root).some(x=>x.tag==='button'&&textOf(x)==='打开草稿'),false);input.props.onInput({target:{value:'公开任务'}});await settle();assert.ok(walk(mounted.root).some(x=>x.tag==='button'&&textOf(x)==='打开草稿'));assert.equal(o.h.assignmentPage.loadedCount,1);}finally{mounted.close();}}finally{o.close();}});
test('fixed version detail rejects public title that contradicts its installed immutable version summary',async()=>{const changed=clone(f.version);changed.public_spec.title='DIFFERENT_TITLE';const o=owner({api:apiFactory({getVersion:async()=>changed})});try{await o.h.loadAssignments();await o.h.selectAssignment('assignment-A');assert.equal(await o.h.selectVersion('version-A'),false);assert.equal(o.h.version.data,null);assert.equal(o.h.version.status,'error');assert.equal(o.h.version.error.reason,'invalid_response');}finally{o.close();}});
