// Official Vue compiler/custom renderer only, with synthetic focus/scroll geometry.
// No browser pixels, document runtime, application entry, backend or live API.
import test from 'node:test';
import assert from 'node:assert/strict';
import * as Vue from 'vue';
import { compile } from '@vue/compiler-dom';
import { readFileSync } from 'node:fs';
import AssignmentWorkspace from '../js/components/teaching/TeachingAssignmentReadWorkspace.js';
import SubmissionWorkspace from '../js/components/teaching/TeachingSubmissionReadWorkspace.js';
import { useTeachingAssignments } from '../js/hooks/useTeachingAssignments.js';
import { useTeachingSubmissions } from '../js/hooks/useTeachingSubmissions.js';
import { fixtures as f,clone,deferred } from './fixtures/teachingAssessmentFixtures.mjs';
const ctx=(extra={})=>({authVerified:true,authEpoch:1,contextEpoch:7,actorId:'student-A',currentRole:'student',offeringId:'offering-A',courseId:'course-A',roleScope:'offering',configuredPermissions:['AUTHOR','RELEASE','SUBMISSION_VIEW'],projection:'fresh',mode:'teaching',modes:['teaching'],b1:{readReady:true},assignments:{readReady:true,reason:'write_safety_unproven'},mutationAllowed:false,...extra});
const apiFactory=(extra={})=>({listAssignments:async()=>clone(f.assignmentPage),getDraft:async()=>clone(f.draft),listVersions:async()=>clone(f.versionPage),getVersion:async()=>clone(f.version),listReleases:async()=>clone(f.releasePage),getRelease:async()=>clone(f.release),getOwnHead:async()=>clone(f.head),listOwnHistory:async()=>clone(f.history),listTeacherSubmissions:async(_id,q)=>clone(Object.hasOwn(q,'studentId')?f.teacherHistory:f.teacherHeads),getSubmission:async()=>clone(f.submission),...extra});
function assignmentOwner(extra={}){const context=Vue.ref(ctx(extra.context)),active=Vue.ref(true),scope=Vue.effectScope();let workspace;scope.run(()=>workspace=useTeachingAssignments({context,active,api:apiFactory(extra.api)}));return{workspace,context,active,close:()=>scope.stop()};}
function submissionOwner(extra={}){const context=Vue.ref(ctx({mode:'learning',modes:['learning'],roleScope:null,...extra.context})),scope=Vue.effectScope(),selection=Vue.ref({releaseId:'release-A',release:{status:'ready',data:clone(f.release)}});let workspace;scope.run(()=>workspace=useTeachingSubmissions({context,active:Vue.ref(true),selection,api:apiFactory(extra.api)}));return{workspace,context,selection,assignments:{release:selection.value.release,releasePage:{status:'ready',items:[clone(f.release)],nextCursor:null,loadedCount:1},selection:{releaseId:'release-A'}},close:()=>scope.stop()};}
const settle=async()=>{await Vue.nextTick();await new Promise(resolve=>setImmediate(resolve));await Vue.nextTick();};
const walk=el=>[el,...el.children.flatMap(walk)],textOf=el=>el.tag==='#comment'?'':el.text+el.children.map(textOf).join('');
const hasClass=(el,value)=>String(el.props.class||'').split(/\s+/).includes(value);
function host({headingTop=1590,headingHeight=26,mainTop=64,mainHeight=736,scrollTop=0,scrollLeft=13}={}){
 const calls=[],scrolls=[],doc={activeElement:null,body:{isConnected:true}},geometry={headingTop,headingHeight,mainTop,mainHeight};doc.activeElement=doc.body;
 function node(tag='',text=''){let scroll=scrollTop;return Vue.markRaw({tag,text,props:{},children:[],parent:null,ownerDocument:doc,clientTop:0,clientHeight:mainHeight,scrollLeft,
  get isConnected(){let current=this;while(current){if(current.tag==='root')return true;current=current.parent;}return false;},
  get scrollTop(){return scroll;},set scrollTop(value){scrolls.push({element:this,top:value,left:this.scrollLeft});scroll=value;},
  contains(el){return walk(this).includes(el);},querySelector(selector){return selector==='[data-tw-read-heading]'?walk(this).find(el=>Object.hasOwn(el.props,'data-tw-read-heading'))||null:null;},
  closest(selector){let el=this;while(el){if(selector==='.tw-content'&&hasClass(el,'tw-content'))return el;el=el.parent;}return null;},
  getBoundingClientRect(){const main=this.closest('.tw-content');return hasClass(this,'tw-content')?{top:geometry.mainTop,bottom:geometry.mainTop+geometry.mainHeight}:{top:geometry.headingTop-(main?.scrollTop||0),bottom:geometry.headingTop-(main?.scrollTop||0)+geometry.headingHeight};},
  focus(options){calls.push({element:this,options});doc.activeElement=this;}});}
 const renderer=Vue.createRenderer({createElement:tag=>node(tag),createText:text=>node('#text',text),createComment:text=>node('#comment',text),setText:(el,text)=>el.text=text,setElementText:(el,text)=>{el.text=text;el.children=[];},parentNode:el=>el.parent,nextSibling:el=>el.parent?.children[el.parent.children.indexOf(el)+1]||null,insert(el,parent,anchor){if(el.parent){const i=el.parent.children.indexOf(el);if(i>=0)el.parent.children.splice(i,1);}el.parent=parent;const i=anchor?parent.children.indexOf(anchor):-1;if(i<0)parent.children.push(el);else parent.children.splice(i,0,el);},remove(el){if(el.parent){const i=el.parent.children.indexOf(el);if(i>=0)el.parent.children.splice(i,1);if(el.contains(doc.activeElement))doc.activeElement=doc.body;el.parent=null;}},patchProp:(el,key,_old,value)=>el.props[key]=value});
 return{node,renderer,doc,calls,scrolls,geometry};
}
const compiled=C=>({...C,components:Object.fromEntries(Object.entries(C.components||{}).map(([key,value])=>[key,compiled(value)])),render:Object.assign(new Function('Vue',compile(C.template,{mode:'function'}).code)(Vue),{_rc:true})});
async function mount(C,props,options={}){const h=host(options),component=compiled(C),root=h.node('root'),errors=[],warnings=[];let vm;const app=h.renderer.createApp({render:()=>Vue.h('main',{class:'tw-content'},[Vue.h(component,{...props,ref:value=>vm=value})])});app.config.errorHandler=e=>errors.push(e);app.config.warnHandler=e=>warnings.push(e);app.mount(root);await settle();return{...h,root,get vm(){return vm;},main:root.children[0],close(){app.unmount();assert.deepEqual(errors,[]);assert.deepEqual(warnings,[]);}};}
const button=(v,label,index=0)=>walk(v.root).filter(el=>el.tag==='button'&&textOf(el)===label)[index];
const click=(v,el)=>{assert.ok(el,'Actual selection control must exist');v.doc.activeElement=el;return el.props.onClick();};
const select=(v,kind,id,label='打开草稿')=>{v.doc.activeElement=button(v,label);return v.vm.choose(kind,id);};
const heading=v=>walk(v.root).find(el=>el.tag==='h2'&&Object.hasOwn(el.props,'data-tw-read-heading')&&el.closest('.tw-content'));
const assertFocused=(v,label)=>{assert.equal(v.calls.length,1,'Successful explicit detail opening must focus exactly one heading');const target=v.calls[0].element;assert.equal(target.tag,'h2');assert.equal(target.props.tabindex,'-1');assert.ok(Object.hasOwn(target.props,'data-tw-read-heading'));assert.deepEqual(v.calls[0].options,{preventScroll:true});assert.equal(v.doc.activeElement,target);if(label)assert.match(textOf(target),label);return target;};
const assignmentView=(o,extra={},options={})=>mount(AssignmentWorkspace,{workspace:o.workspace,...extra},options);
const submissionView=(o,extra={},options={})=>mount(SubmissionWorkspace,{workspace:o.workspace,assignments:o.assignments,...extra},options);

test('explicit draft opening focuses installed title and exposes offscreen heading through owned main only',async()=>{const o=assignmentOwner();try{await o.workspace.loadAssignments();const v=await assignmentView(o);try{await click(v,button(v,'打开草稿'));await settle();const title=assertFocused(v,/公开任务/),rect=title.getBoundingClientRect();assert.ok(rect.top>=64&&rect.bottom<=800);assert.equal(v.scrolls.length,1);assert.equal(v.scrolls[0].element,v.main);assert.equal(v.main.scrollLeft,13);}finally{v.close();}}finally{o.close();}});
test('explicit fixed version opening hands focus to current title with no scroll when already visible',async()=>{const o=assignmentOwner();try{await o.workspace.loadAssignments();await o.workspace.selectAssignment('assignment-A');const v=await assignmentView(o,{}, {headingTop:240});try{await click(v,button(v,'打开固定版本'));await settle();assertFocused(v,/公开任务/);assert.deepEqual(v.scrolls,[]);}finally{v.close();}}finally{o.close();}});
test('explicit public release opening focuses its current plain text title',async()=>{const o=assignmentOwner({context:{mode:'learning',modes:['learning'],roleScope:null}});try{await o.workspace.loadReleases();const v=await assignmentView(o);try{await click(v,button(v,'打开发布记录'));await settle();assertFocused(v,/公开任务/);assert.ok(textOf(v.root).includes('<script>inert</script>'));assert.equal(walk(v.root).some(el=>el.tag==='script'),false);}finally{v.close();}}finally{o.close();}});
test('explicit own history detail focuses submission heading instead of release preview',async()=>{const o=submissionOwner();try{await o.workspace.refresh();const v=await submissionView(o);try{await click(v,button(v,'查看记录',1));await settle();assertFocused(v,/序列 2/);assert.ok(textOf(v.root).includes(f.submission.content.text));}finally{v.close();}}finally{o.close();}});
test('explicit own current head opens the same submission focus handoff',async()=>{const o=submissionOwner();try{await o.workspace.refresh();const v=await submissionView(o);try{await click(v,button(v,'查看当前头'));await settle();assertFocused(v,/序列 2/);}finally{v.close();}}finally{o.close();}});
test('explicit exact teacher history detail focuses only independently installed submission',async()=>{const o=submissionOwner({context:{mode:'teaching',modes:['teaching'],roleScope:'offering'},api:{getSubmission:async()=>clone(f.teacherSubmission)}});try{await o.workspace.loadTeacherHistory('student-A');const v=await submissionView(o);try{await click(v,button(v,'查看记录',1));await settle();assertFocused(v,/序列 2/);assert.equal(o.workspace.detail.data.student_id,'student-A');}finally{v.close();}}finally{o.close();}});
test('heading above current main scroll viewport becomes visible without horizontal movement',async()=>{const o=assignmentOwner();try{await o.workspace.loadAssignments();const v=await assignmentView(o,{}, {headingTop:240,scrollTop:300});try{await click(v,button(v,'打开草稿'));await settle();const title=assertFocused(v);assert.ok(title.getBoundingClientRect().top>=64);assert.ok(v.main.scrollTop<300);assert.equal(v.main.scrollLeft,13);}finally{v.close();}}finally{o.close();}});
test('preinstalled detail including initial locator presentation never takes focus',async()=>{const o=assignmentOwner();try{await o.workspace.loadAssignments();await o.workspace.selectAssignment('assignment-A');const v=await assignmentView(o);try{assert.deepEqual(v.calls,[]);assert.deepEqual(v.scrolls,[]);}finally{v.close();}}finally{o.close();}});
test('direct background detail installs refresh and list paging never take focus',async()=>{let pages=0;const o=assignmentOwner({api:{listAssignments:async()=>++pages===1?{...clone(f.assignmentPage),next_cursor:'AAAA'}:{items:[{...clone(f.author),id:'assignment-B'}],next_cursor:null,as_of:'2026-10-04T04:30:00.123456Z'}}});try{await o.workspace.loadAssignments();const v=await assignmentView(o);try{await o.workspace.selectAssignment('assignment-A');await settle();assert.deepEqual(v.calls,[]);await click(v,button(v,'继续读取作业'));await settle();assert.deepEqual(v.calls,[]);await click(v,button(v,'重新读取任务'));await settle();assert.deepEqual(v.calls,[]);assert.deepEqual(v.scrolls,[]);}finally{v.close();}}finally{o.close();}});
test('successful history release selection refreshes lists without focusing public preview',async()=>{const o=submissionOwner();try{const v=await submissionView(o,{navigation:{selectRelease:async()=>{await o.workspace.refresh();return true;}}});try{await click(v,button(v,'打开发布记录'));await settle();assert.deepEqual(v.calls,[]);assert.deepEqual(v.scrolls,[]);}finally{v.close();}}finally{o.close();}});
test('current errors and authority denials never focus or scroll a missing detail',async()=>{for(const status of [401,403,404,503]){const o=assignmentOwner({api:{getDraft:async()=>{throw{status,reason:status===503?'database_unavailable':'permission_denied'};}}});try{await o.workspace.loadAssignments();const v=await assignmentView(o);try{assert.equal(await select(v,'selectAssignment','assignment-A'),false);await settle();assert.deepEqual(v.calls,[],String(status));assert.deepEqual(v.scrolls,[]);assert.equal(o.workspace.draft.data,null);}finally{v.close();}}finally{o.close();}}});
test('false navigation result leaves preexisting detail and focus unchanged',async()=>{const o=assignmentOwner();try{await o.workspace.loadAssignments();await o.workspace.selectAssignment('assignment-A');const v=await assignmentView(o,{navigation:{selectAssignment:async()=>false}});try{const trigger=button(v,'打开草稿');assert.equal(await select(v,'selectAssignment','assignment-A'),false);await settle();assert.equal(v.doc.activeElement,trigger);assert.deepEqual(v.calls,[]);assert.deepEqual(v.scrolls,[]);}finally{v.close();}}finally{o.close();}});
test('newer explicit intent fences prior successful completion and focuses only newest detail',async()=>{const old=deferred(),fresh=deferred();let n=0;const o=assignmentOwner({api:{getDraft:()=>++n===1?old.promise:fresh.promise}});try{await o.workspace.loadAssignments();const v=await assignmentView(o);try{const trigger=button(v,'打开草稿'),a=select(v,'selectAssignment','assignment-A'),b=select(v,'selectAssignment','assignment-A');old.resolve(clone(f.draft));assert.equal(await a,false);assert.deepEqual(v.calls,[]);fresh.resolve(clone(f.draft));assert.equal(await b,true);await settle();assertFocused(v);}finally{v.close();}}finally{o.close();}});
test('authority changes during pending explicit read block late focus and content',async()=>{const pending=deferred(),o=assignmentOwner({api:{getDraft:()=>pending.promise}});try{await o.workspace.loadAssignments();const v=await assignmentView(o);try{const read=select(v,'selectAssignment','assignment-A');o.context.value=ctx({authEpoch:2});pending.resolve(clone(f.draft));assert.equal(await read,false);await settle();assert.deepEqual(v.calls,[]);assert.deepEqual(v.scrolls,[]);assert.equal(o.workspace.draft.data,null);}finally{v.close();}}finally{o.close();}});
test('unmounted workspace fences focus even when its separate owner installs a late success',async()=>{const pending=deferred(),o=assignmentOwner({api:{getDraft:()=>pending.promise}});try{await o.workspace.loadAssignments();const v=await assignmentView(o);const read=select(v,'selectAssignment','assignment-A');v.close();pending.resolve(clone(f.draft));assert.equal(await read,true);await settle();assert.deepEqual(v.calls,[]);assert.deepEqual(v.scrolls,[]);}finally{o.close();}});
test('focus moved intentionally to another connected control is preserved while detail loads',async()=>{const pending=deferred(),o=assignmentOwner({api:{getDraft:()=>pending.promise}});try{await o.workspace.loadAssignments();const v=await assignmentView(o);try{const read=select(v,'selectAssignment','assignment-A'),other=button(v,'重新读取任务');other.focus();v.calls.length=0;pending.resolve(clone(f.draft));assert.equal(await read,true);await settle();assert.equal(v.doc.activeElement,other);assert.deepEqual(v.calls,[]);assert.deepEqual(v.scrolls,[]);}finally{v.close();}}finally{o.close();}});
test('body fallback from a removed origin control permits successful current detail focus',async()=>{const o=assignmentOwner();try{await o.workspace.loadAssignments();const v=await assignmentView(o,{navigation:{selectAssignment:async id=>{const origin=v.doc.activeElement;const result=await o.workspace.selectAssignment(id);origin.parent.children.splice(origin.parent.children.indexOf(origin),1);origin.parent=null;v.doc.activeElement=v.doc.body;return result;}}});try{await click(v,button(v,'打开草稿'));await settle();assertFocused(v);}finally{v.close();}}finally{o.close();}});
test('user choosing body while connected origin remains does not trigger late focus',async()=>{const pending=deferred(),o=assignmentOwner({api:{getDraft:()=>pending.promise}});try{await o.workspace.loadAssignments();const v=await assignmentView(o);try{const read=select(v,'selectAssignment','assignment-A');v.doc.activeElement=v.doc.body;pending.resolve(clone(f.draft));await read;await settle();assert.deepEqual(v.calls,[]);assert.deepEqual(v.scrolls,[]);}finally{v.close();}}finally{o.close();}});
test('background invalidation queued after read success prevents nextTick focus',async()=>{const o=assignmentOwner();try{await o.workspace.loadAssignments();const v=await assignmentView(o,{navigation:{selectAssignment:async id=>{const result=await o.workspace.selectAssignment(id);Vue.nextTick(()=>o.workspace.clear());return result;}}});try{await click(v,button(v,'打开草稿'));await settle();assert.deepEqual(v.calls,[]);assert.deepEqual(v.scrolls,[]);}finally{v.close();}}finally{o.close();}});
test('explicit retry of failed current detail focuses only newly accepted title',async()=>{let n=0;const o=assignmentOwner({api:{getDraft:async()=>{if(++n===1)throw{status:503,reason:'database_unavailable'};return clone(f.draft);}}});try{await o.workspace.loadAssignments();const v=await assignmentView(o);try{await click(v,button(v,'打开草稿'));await settle();assert.deepEqual(v.calls,[]);await click(v,button(v,'重试读取'));await settle();assertFocused(v);}finally{v.close();}}finally{o.close();}});
test('focus style remains scoped and preserves visible cinnabar heading focus',()=>{const css=readFileSync(new URL('../styles/teaching-workbench.css',import.meta.url),'utf8');assert.match(css,/\.teaching-workbench \[data-tw-read-heading\]:focus\s*\{[^}]*outline:3px solid var\(--tw-accent\)/);});
