// Tranche C: immutable synthetic wire fixtures, official Vue no-DOM runtime.
import test from 'node:test';
import assert from 'node:assert/strict';
import * as Vue from 'vue';
import { fixtures as f,clone,deferred,at } from './fixtures/teachingAssessmentFixtures.mjs';
let useTeachingSubmissions;
try{({useTeachingSubmissions}=await import('../js/hooks/useTeachingSubmissions.js'));}catch(error){if(error.code!=='ERR_MODULE_NOT_FOUND')throw error;}
const feature=()=>assert.equal(typeof useTeachingSubmissions,'function','Fenced Tranche C submission read owner must exist');
const ctx=(extra={})=>({authVerified:true,authEpoch:1,contextEpoch:7,actorId:'student-A',currentRole:'student',offeringId:'offering-A',roleScope:null,configuredPermissions:[],projection:'fresh',mode:'learning',modes:['learning'],b1:{readReady:true},assignments:{readReady:true,reason:'write_safety_unproven'},...extra});
const teacher=(extra={})=>ctx({mode:'teaching',modes:['teaching'],roleScope:'offering',configuredPermissions:['SUBMISSION_VIEW'],...extra});
const selected=()=>({releaseId:'release-A',release:{status:'ready',data:clone(f.release)}});
const apiFactory=(changes={})=>({getRelease:async()=>clone(f.release),getOwnHead:async()=>clone(f.head),listOwnHistory:async()=>clone(f.history),listTeacherSubmissions:async(_id,q)=>clone(Object.hasOwn(q,'studentId')?f.teacherHistory:f.teacherHeads),getSubmission:async()=>clone(f.submission),...changes});
function owner({context=ctx(),active=true,selection=selected(),api=apiFactory()}={}){feature();const c=Vue.ref(context),a=Vue.ref(active),s=Vue.ref(selection),scope=Vue.effectScope();let h;scope.run(()=>h=useTeachingSubmissions({context:c,active:a,selection:s,api}));return{h,c,a,s,close:()=>scope.stop()};}
const firstPage={items:[clone(f.first)],current_head_id:'submission-B',next_cursor:'AAAA',as_of:at};
const secondPage={items:[clone(f.second)],current_head_id:'submission-B',next_cursor:null,as_of:'2026-10-04T04:31:00.654321Z'};
const assertClear=h=>{for(const k of ['ownHistory','teacherHeads','teacherHistory']){assert.equal(h[k].items.length,0);assert.equal(h[k].nextCursor,null);}assert.equal(h.head.data,null);assert.equal(h.detail.data,null);assert.equal(h.selectedSubmissionId.value,null);};

test('entry is shared local access and sends zero reads before ready active installed release',async()=>{for(const options of [{active:false},{context:ctx({authVerified:false})},{context:ctx({assignments:{readReady:false}})},{context:teacher({configuredPermissions:['RELEASE']})},{context:teacher({roleScope:'assigned'})},{selection:{releaseId:'release-A',release:{status:'idle',data:null}}}]){let calls=0;const o=owner({...options,api:apiFactory(Object.fromEntries(['getRelease','getOwnHead','listOwnHistory','listTeacherSubmissions','getSubmission'].map(k=>[k,async()=>{calls++;throw Error('unexpected');}])))});try{await o.h.refresh();await o.h.loadTeacherHistory('student-A');assert.equal(calls,0);}finally{o.close();}}});
test('own head history and separately authorized detail preserve exact wire facts and no selector',async()=>{const calls=[],o=owner({api:apiFactory({getRelease:async()=>{calls.push('release');return clone(f.release);},getOwnHead:async(id,q)=>{calls.push(['head',id,q]);return clone(f.head);},listOwnHistory:async(id,q)=>{calls.push(['history',id,q]);return clone(f.history);},getSubmission:async(id,q)=>{calls.push(['detail',id,q]);return clone(f.submission);}})});try{assert.equal(await o.h.refresh(),true);assert.equal(o.h.head.data.as_of,at);assert.equal(o.h.ownHistory.currentHeadId,'submission-B');assert.equal(await o.h.selectSubmission('submission-B'),true);assert.equal(o.h.detail.data.content.text,f.submission.content.text);assert.equal(o.h.detail.data.ai_usage_declaration.description,f.submission.ai_usage_declaration.description);for(const call of calls.filter(Array.isArray))assert.equal(Object.hasOwn(call[2],'studentId'),false);assert.equal(calls.filter(x=>x==='release').length,3);}finally{o.close();}});
test('null initial head is an accepted fact unlike missing malformed or failed head',async()=>{for(const [reply,status] of [[f.emptyHead,'empty'],[null,'error'],[{...f.head,revision:0},'error']]){const o=owner({api:apiFactory({getOwnHead:async()=>clone(reply)})});try{assert.equal(await o.h.loadOwnHead(),status==='empty');assert.equal(o.h.head.status,status);assert.equal(o.h.head.data?.submission_id??null,null);}finally{o.close();}}const o=owner({api:apiFactory({getOwnHead:async()=>{throw{status:503,reason:'invalid_assessment_state'};}})});try{await o.h.loadOwnHead();assert.equal(o.h.head.status,'error');assert.equal(o.h.head.data,null);}finally{o.close();}});
test('head is independent of history captured head outside loaded page and microsecond as_of',async()=>{let n=0;const o=owner({api:apiFactory({listOwnHistory:async()=>clone(++n===1?firstPage:secondPage)})});try{await o.h.loadOwnHead();await o.h.loadOwnHistory({limit:1});assert.equal(o.h.ownHistory.loadedCount,1);assert.equal(o.h.ownHistory.currentHeadId,'submission-B');assert.equal(o.h.head.data.revision,2);await o.h.loadMore('ownHistory');assert.equal(o.h.ownHistory.loadedCount,2);assert.equal(o.h.head.data.as_of,at);assert.equal(o.h.ownHistory.asOf,secondPage.as_of);}finally{o.close();}});
test('teacher heads and exact filtered history own distinct query cursors and captured head',async()=>{const calls=[],o=owner({context:teacher(),api:apiFactory({listTeacherSubmissions:async(id,q)=>{calls.push([id,q]);return clone(Object.hasOwn(q,'studentId')?f.teacherHistory:{...f.teacherHeads,next_cursor:'AAAA'});},getSubmission:async()=>clone(f.teacherSubmission)})});try{await o.h.loadTeacherHeads({limit:2});assert.equal(o.h.teacherHeads.currentHeadId,null);assert.equal(await o.h.loadTeacherHistory('student-A',{limit:1}),true);assert.equal(o.h.studentId.value,'student-A');assert.equal(o.h.teacherHistory.currentHeadId,'submission-B');assert.equal(o.h.teacherHeads.nextCursor,'AAAA');assert.equal(await o.h.selectSubmission('submission-B'),true);assert.equal(o.h.detail.data.student_id,'student-A');assert.equal(Object.hasOwn(calls[0][1],'studentId'),false);assert.equal(calls[1][1].studentId,'student-A');}finally{o.close();}});
test('teacher selector accepts full exact 255 codepoints including reserved Unicode and rejects normalization',async()=>{const subject='😀'.repeat(247)+'/\\%?# 空格',calls=[];assert.equal([...subject].length,255);const o=owner({context:teacher(),api:apiFactory({listTeacherSubmissions:async(_id,q)=>{calls.push(q.studentId);return clone(f.emptyTeacherHistory);}})});try{assert.equal(await o.h.loadTeacherHistory(subject),true);assert.deepEqual(calls,[subject]);for(const bad of [null,'',' student-A','student-A ','a\n','😀'.repeat(256)])assert.equal(await o.h.loadTeacherHistory(bad),false);assert.equal(calls.length,1);}finally{o.close();}});
test('unknown and out of ceiling selectors show the same empty/null without detail or identity lookup',async()=>{const o=owner({context:teacher(),api:apiFactory({listTeacherSubmissions:async()=>clone(f.emptyTeacherHistory),getSubmission:async()=>{throw Error('No existence probe');}})});try{for(const subject of ['unknown','out-of-ceiling']){await o.h.loadTeacherHistory(subject);assert.equal(o.h.teacherHistory.status,'empty');assert.equal(o.h.teacherHistory.currentHeadId,null);assert.equal(await o.h.selectSubmission('submission-A'),false);}}finally{o.close();}});
test('teacher own projection is accepted only for current exact actor and never invents student_id',async()=>{for(const subject of ['student-A','other']){const rows=clone(f.teacherHistory);rows.items.forEach(x=>x.student_id=subject);const o=owner({context:teacher(),api:apiFactory({listTeacherSubmissions:async()=>rows})});try{await o.h.loadTeacherHistory(subject);assert.equal(await o.h.selectSubmission('submission-B'),subject==='student-A');assert.equal(Object.hasOwn(o.h.detail.data||{},'student_id'),false);}finally{o.close();}}});
test('own mode refuses teacher projection and teacher exact selector refuses another subject',async()=>{for(const options of [{api:apiFactory({getSubmission:async()=>clone(f.teacherSubmission)})},{context:teacher(),api:apiFactory({getSubmission:async()=>({...clone(f.teacherSubmission),student_id:'other'})})}]){const o=owner(options);try{if(options.context)await o.h.loadTeacherHistory('student-A');else await o.h.loadOwnHistory();assert.equal(await o.h.selectSubmission('submission-B'),false);assert.equal(o.h.detail.data,null);}finally{o.close();}}});
test('every entry reauthorizes release current public projection spec and immutable offering version chain',async()=>{for(const mutate of [r=>r.id='other',r=>r.version.offering_id='other',r=>r.version.id='other',r=>r.version.public_spec.instructions='changed',r=>r.version.public_spec_hash='b'.repeat(64),r=>Object.assign(r,{recipient_count:1,recipient_digest:'b'.repeat(64)})]){let calls=0;const data=clone(f.release);mutate(data);const o=owner({api:apiFactory({getRelease:async()=>data,listOwnHistory:async()=>{calls++;return clone(f.history);}})});try{assert.equal(await o.h.loadOwnHistory(),false);assert.equal(calls,0);assert.equal(o.h.ownHistory.items.length,0);}finally{o.close();}}});
test('detail must match selected immutable summary including sequence parent hash time and release version',async()=>{for(const [key,value] of Object.entries({id:'other',release_id:'other',version_id:'other',sequence:3,parent_submission_id:'other',content_hash:'b'.repeat(64),received_at:'2026-10-04T04:30:00.123457Z'})){const o=owner({api:apiFactory({getSubmission:async()=>({...clone(f.submission),[key]:value})})});try{await o.h.loadOwnHistory();assert.equal(await o.h.selectSubmission('submission-B'),false,key);assert.equal(o.h.detail.data,null);}finally{o.close();}}});
test('head-only detail is independently authorized and matches exact captured revision',async()=>{const o=owner();try{await o.h.loadOwnHead();assert.equal(await o.h.selectSubmission('submission-B'),true);assert.equal(o.h.detail.data.sequence,2);assert.equal(o.h.ownHistory.items.length,0);}finally{o.close();}const o2=owner({api:apiFactory({getOwnHead:async()=>({...clone(f.head),revision:3})})});try{await o2.h.loadOwnHead();assert.equal(await o2.h.selectSubmission('submission-B'),false);}finally{o2.close();}});
test('invalid newer selection cancels old detail success errors and finally',async()=>{for(const failure of [false,true]){const pending=deferred(),o=owner({api:apiFactory({getSubmission:()=>pending.promise})});try{await o.h.loadOwnHistory();const old=o.h.selectSubmission('submission-B');await Promise.resolve();await o.h.selectSubmission('not-installed');if(failure)pending.reject({status:403,reason:'permission_denied'});else pending.resolve(clone(f.submission));assert.equal(await old,false);assert.equal(o.h.detail.status,'error');assert.equal(o.h.detail.data,null);}finally{o.close();}}});
test('authority and installed release changes synchronously erase rows bodies titles selections and cursors',async()=>{for(const extra of [{authEpoch:2},{contextEpoch:8},{actorId:'other'},{offeringId:'other'},{mode:'teaching',modes:['teaching'],roleScope:'offering',configuredPermissions:['SUBMISSION_VIEW']},{projection:'new'},{assignments:{readReady:false}},{b1:{readReady:false}},{authVerified:false}]){const o=owner();try{await o.h.refresh();await o.h.selectSubmission('submission-B');o.c.value=ctx(extra);assertClear(o.h);}finally{o.close();}}const o=owner();try{await o.h.refresh();o.s.value={releaseId:null,release:{status:'idle',data:null}};assertClear(o.h);o.a.value=false;assertClear(o.h);}finally{o.close();}});
test('old success 401 denial and finally cannot override a newer loading head or query',async()=>{for(const failure of [false,true]){const old=deferred(),fresh=deferred();let n=0;const o=owner({api:apiFactory({getOwnHead:()=>++n===1?old.promise:fresh.promise})});try{const a=o.h.loadOwnHead();await Promise.resolve();o.c.value=ctx({contextEpoch:8});const b=o.h.loadOwnHead();await Promise.resolve();if(failure)old.reject({status:401,reason:'unauthenticated'});else old.resolve(clone(f.head));await a;assert.equal(o.h.head.status,'loading');assert.equal(o.h.head.data,null);fresh.resolve(clone(f.head));assert.equal(await b,true);}finally{o.close();}}});
test('selector switch fences stale teacher pagination and detail without reusing head cursor',async()=>{const pending=deferred();let calls=0;const o=owner({context:teacher(),api:apiFactory({listTeacherSubmissions:async(_id,q)=>{calls++;if(q.studentId==='student-A'&&q.cursor)return pending.promise;if(q.studentId==='student-A')return{...clone(f.teacherHistory),items:[{...clone(f.first),student_id:'student-A'}],next_cursor:'AAAA'};return clone(f.emptyTeacherHistory);}})});try{await o.h.loadTeacherHistory('student-A');const old=o.h.loadMore('teacherHistory');await Promise.resolve();await o.h.loadTeacherHistory('other');pending.resolve(clone(f.teacherHistory));assert.equal(await old,false);assert.equal(o.h.studentId.value,'other');assert.equal(o.h.teacherHistory.items.length,0);assert.equal(o.h.teacherHistory.nextCursor,null);assert.equal(o.h.detail.data,null);assert.equal(calls,3);}finally{o.close();}});
test('foreign cursor query limit unknown option or resource cannot expand selection',async()=>{const o=owner({api:apiFactory({listOwnHistory:async()=>clone(firstPage)})});try{await o.h.loadOwnHistory({limit:1});for(const q of [{cursor:'AAAA',limit:2},{cursor:'AAAB'},{studentId:'student-A'},{limit:101},{cursor:null}]){assert.equal(await o.h.loadOwnHistory(q),false);assert.equal(o.h.ownHistory.items.length,0);await o.h.loadOwnHistory({limit:1});}assert.equal(await o.h.loadMore('private'),false);}finally{o.close();}});
test('duplicate out-of-order or broken adjacent chain pages reject without installing bodies',async()=>{for(const data of [{...secondPage,items:[clone(f.first)]},{...secondPage,items:[{...clone(f.second),parent_submission_id:'wrong'}]},{...secondPage,items:[{...clone(f.second),release_id:'wrong'}]}]){let n=0;const o=owner({api:apiFactory({listOwnHistory:async()=>clone(++n===1?firstPage:data)})});try{await o.h.loadOwnHistory({limit:1});assert.equal(await o.h.loadMore('ownHistory'),false);assert.equal(o.h.ownHistory.status,'error');assert.equal(o.h.ownHistory.loadedCount,1);assert.equal(o.h.ownHistory.partial,true);}finally{o.close();}}});
test('same authority non-auth pagination failure is stale partial but current denial clears all',async()=>{for(const status of [503,401,403,404]){let n=0;const o=owner({api:apiFactory({listOwnHistory:async()=>{if(++n===1)return clone(firstPage);throw{status,reason:status===503?'database_unavailable':status===401?'unauthenticated':status===404?'not_found':'permission_denied'};}})});try{await o.h.loadOwnHead();await o.h.loadOwnHistory({limit:1});await o.h.selectSubmission('submission-B');await o.h.loadMore('ownHistory');if(status===503){assert.equal(o.h.ownHistory.items.length,1);assert.equal(o.h.ownHistory.partial,true);}else{assertClear(o.h);assert.equal(o.h.ownHistory.status,'unavailable');}}finally{o.close();}}});
test('same-token current membership withdrawal release denial clears accepted descendants',async()=>{let deny=false;const o=owner({api:apiFactory({getRelease:async()=>{if(deny)throw{status:403,reason:'permission_denied'};return clone(f.release);}})});try{await o.h.refresh();await o.h.selectSubmission('submission-B');deny=true;assert.equal(await o.h.loadOwnHistory(),false);assertClear(o.h);assert.equal(o.h.ownHistory.status,'unavailable');}finally{o.close();}});
test('unmount cancels late reads and detail has no effect afterward',async()=>{const wait=deferred(),o=owner({api:apiFactory({listOwnHistory:()=>wait.promise})});const old=o.h.loadOwnHistory();await Promise.resolve();o.close();wait.resolve(clone(f.history));assert.equal(await old,false);assertClear(o.h);assert.equal(await o.h.selectSubmission('submission-B'),false);});

test('empty intermediary page cannot erase accepted sequence boundary for later continuation',async()=>{let n=0;const pages=[firstPage,{items:[],current_head_id:'submission-B',next_cursor:'BBBB',as_of:at},{items:[{...clone(f.first),id:'submission-C'}],current_head_id:'submission-B',next_cursor:null,as_of:at}];const o=owner({api:apiFactory({listOwnHistory:async()=>clone(pages[n++])})});try{await o.h.loadOwnHistory({limit:1});assert.equal(await o.h.loadMore('ownHistory'),true);assert.equal(await o.h.loadMore('ownHistory'),false);assert.equal(o.h.ownHistory.items.length,1);assert.equal(o.h.ownHistory.status,'error');}finally{o.close();}});

test('real approved GET adapters preserve exact teacher URL subject and never attempt private roster mutation or own selector',async()=>{
 const {teachingAssignmentsApi}=await import('../js/api/teachingAssignments.js');
 const {wire}=await import('./fixtures/teachingAssessmentFixtures.mjs');
 const subject='😀'.repeat(247)+'/\\%?# 空格',urls=[],oldFetch=globalThis.fetch;
 localStorage.setItem('token','synthetic-tranche-c');
 globalThis.fetch=async(url,options)=>{urls.push([String(url),options.method]);const u=new URL(url);if(u.pathname.endsWith('/releases/release-A'))return wire(clone(f.release));if(u.pathname.endsWith('/submissions')){const selected=u.searchParams.get('student_id');return wire(selected===null?clone(f.teacherHeads):{...clone(f.teacherHistory),items:clone(f.teacherHistory.items).map(row=>({...row,student_id:selected}))});}if(u.pathname.endsWith('/my-submission-head'))return wire(clone(f.head));if(u.pathname.endsWith('/my-submissions'))return wire(clone(f.history));if(u.pathname.endsWith('/submissions/submission-B'))return wire(clone(f.submission));throw Error('Unexpected endpoint');};
 const t=owner({context:teacher(),api:teachingAssignmentsApi}),o=owner({api:teachingAssignmentsApi});
 try{assert.equal(await t.h.loadTeacherHeads(),true);assert.equal(await t.h.loadTeacherHistory(subject),true);const filtered=urls.find(([url])=>new URL(url).searchParams.has('student_id'));assert.equal(new URL(filtered[0]).searchParams.get('student_id'),subject);assert.equal(new URL(filtered[0]).searchParams.getAll('student_id').length,1);assert.equal(await o.h.refresh(),true);assert.equal(await o.h.selectSubmission('submission-B'),true);for(const [url,method] of urls){assert.equal(method,'GET');assert.doesNotMatch(url,/private|roster|feedback|preview|recipient|grade|write|publish|submit\?/);if(/my-submission/.test(url))assert.equal(new URL(url).searchParams.has('student_id'),false);}}
 finally{t.close();o.close();globalThis.fetch=oldFetch;localStorage.removeItem('token');}
});
test('malformed history private grade unsafe integer and partial selector DTOs never become empty success',async()=>{for(const change of [p=>p.items[0].grade=0,p=>p.items[0].private_spec='private',p=>p.items[0].sequence=Number.MAX_SAFE_INTEGER+1,p=>delete p.current_head_id,p=>p.items[0].received_at='2026-02-30T00:00:00.123456Z']){const data=clone(f.history);change(data);const o=owner({api:apiFactory({listOwnHistory:async()=>data})});try{assert.equal(await o.h.loadOwnHistory(),false);assert.equal(o.h.ownHistory.status,'error');assert.equal(o.h.ownHistory.loadedCount,0);assert.equal(o.h.ownHistory.items.length,0);}finally{o.close();}}});

test('settled old detail success denial 401 and finally cannot install or finish newer valid detail',async()=>{
 for(const failure of [false,true]){const old=deferred(),fresh=deferred(),started=deferred(),startedNew=deferred();let reads=0;
  const firstDetail={...clone(f.first),content:{kind:'text',language:null,text:'首次原文\r\n😀\n'},ai_usage_declaration:{used_ai:false,description:''}};
  const o=owner({api:apiFactory({getSubmission:id=>{reads++;if(id==='submission-B'){started.resolve();return old.promise;}startedNew.resolve();return fresh.promise;}})});
  try{await o.h.loadOwnHistory();const a=o.h.selectSubmission('submission-B');await started.promise;const b=o.h.selectSubmission('submission-A');await startedNew.promise;if(failure)old.reject({status:401,reason:'unauthenticated'});else old.resolve(clone(f.submission));assert.equal(await a,false);assert.equal(o.h.selectedSubmissionId.value,'submission-A');assert.equal(o.h.detail.status,'loading');assert.equal(o.h.detail.data,null);fresh.resolve(firstDetail);assert.equal(await b,true);assert.equal(o.h.detail.data.id,'submission-A');assert.equal(reads,2);}finally{o.close();}
 }
});
test('teacher selector changes cancel old received detail before new filtered empty history',async()=>{
 const pending=deferred(),started=deferred(),o=owner({context:teacher(),api:apiFactory({listTeacherSubmissions:async(_id,q)=>clone(q.studentId==='student-A'?f.teacherHistory:f.emptyTeacherHistory),getSubmission:()=>{started.resolve();return pending.promise;}})});
 try{await o.h.loadTeacherHistory('student-A');const a=o.h.selectSubmission('submission-B');await started.promise;await o.h.loadTeacherHistory('other');pending.resolve(clone(f.teacherSubmission));assert.equal(await a,false);assert.equal(o.h.detail.data,null);assert.equal(o.h.selectedSubmissionId.value,null);assert.equal(o.h.teacherHistory.status,'empty');assert.equal(o.h.studentId.value,'other');}finally{o.close();}
});
test('head and filtered teacher page cursors remain separate under wrong-mode reuse',async()=>{
 const o=owner({context:teacher(),api:apiFactory({listTeacherSubmissions:async(_id,q)=>Object.hasOwn(q,'studentId')?{...clone(f.teacherHistory),next_cursor:'BBBB'}:{...clone(f.teacherHeads),next_cursor:'AAAA'}})});
 try{await o.h.loadTeacherHeads();await o.h.loadTeacherHistory('student-A');assert.equal(await o.h.loadTeacherHistory('student-A',{cursor:'AAAA'}),false);assert.equal(o.h.teacherHeads.nextCursor,'AAAA');assert.equal(o.h.teacherHistory.items.length,0);assert.equal(o.h.teacherHistory.nextCursor,null);}finally{o.close();}
});
