// Actual mounted Vue/SSR, synthetic responses only. No DOM, main runtime, browser or server.
import test from 'node:test';
import assert from 'node:assert/strict';
import * as Vue from 'vue';
import { compile } from '@vue/compiler-dom';
import { renderToString } from '@vue/server-renderer';
import { readFileSync } from 'node:fs';
import { fixtures as f,clone,at,deferred } from './fixtures/teachingAssessmentFixtures.mjs';
const modules={};for(const [key,path] of Object.entries({hook:'../js/hooks/useTeachingSubmissions.js',workspace:'../js/components/teaching/TeachingSubmissionReadWorkspace.js',shell:'../js/components/teaching/TeachingWorkbenchShell.js',workbench:'../js/hooks/useTeachingWorkbench.js'})){try{modules[key]=await import(path);}catch(error){if(error.code!=='ERR_MODULE_NOT_FOUND')throw error;}}
const feature=()=>{assert.equal(typeof modules.hook?.useTeachingSubmissions,'function','Tranche C owner must exist');assert.ok(modules.workspace?.default,'Actual submission reading workspace must exist');};
const ctx=(extra={})=>({authVerified:true,authEpoch:1,contextEpoch:7,actorId:'student-A',currentRole:'student',offeringId:'offering-A',courseId:'course-A',roleScope:null,configuredPermissions:[],projection:'fresh',mode:'learning',modes:['learning'],b1:{readReady:true},assignments:{readReady:true,reason:'write_safety_unproven'},...extra});
const apiFactory=(overrides={})=>({getRelease:async()=>clone(f.release),getOwnHead:async()=>clone(f.head),listOwnHistory:async()=>clone(f.history),listTeacherSubmissions:async(_id,q)=>clone(Object.hasOwn(q,'studentId')?f.teacherHistory:f.teacherHeads),getSubmission:async()=>clone(f.submission),...overrides});
function owner({context=ctx(),api=apiFactory()}={}){feature();const c=Vue.ref(context),s=Vue.ref({releaseId:'release-A',release:{status:'ready',data:clone(f.release)}}),scope=Vue.effectScope();let h;scope.run(()=>h=modules.hook.useTeachingSubmissions({context:c,active:Vue.ref(true),selection:s,api}));const assignments={access:h.access,release:{status:'ready',data:clone(f.release)},releasePage:{status:'ready',items:[clone(f.release)],nextCursor:null,loadedCount:1},selection:{releaseId:'release-A'}};return{h,c,s,assignments,close:()=>scope.stop()};}
const settle=async()=>{await Vue.nextTick();await new Promise(resolve=>setImmediate(resolve));await Vue.nextTick();};
function node(tag='',text=''){return{tag,text,props:{},children:[],parent:null};}
const renderer=Vue.createRenderer({createElement:tag=>node(tag),createText:text=>node('#text',text),createComment:text=>node('#comment',text),setText:(el,text)=>el.text=text,setElementText:(el,text)=>{el.text=text;el.children=[];},parentNode:el=>el.parent,nextSibling:el=>el.parent?.children[el.parent.children.indexOf(el)+1]||null,insert(el,parent,anchor){if(el.parent){const i=el.parent.children.indexOf(el);if(i>=0)el.parent.children.splice(i,1);}el.parent=parent;const i=anchor?parent.children.indexOf(anchor):-1;if(i<0)parent.children.push(el);else parent.children.splice(i,0,el);},remove(el){if(el.parent){const i=el.parent.children.indexOf(el);if(i>=0)el.parent.children.splice(i,1);el.parent=null;}},patchProp:(el,key,_old,value)=>el.props[key]=value});
const walk=el=>[el,...el.children.flatMap(walk)],textOf=el=>el.tag==='#comment'?'':el.text+el.children.map(textOf).join('');
const compiled=C=>{assert.ok(C,'Actual component required');return{...C,components:Object.fromEntries(Object.entries(C.components||{}).map(([key,value])=>[key,compiled(value)])),render:Object.assign(new Function('Vue',compile(C.template,{mode:'function'}).code)(Vue),{_rc:true})};};
async function mount(C,props){const component=compiled(C),root=node('root'),errors=[],warnings=[];const app=renderer.createApp({render:()=>Vue.h(component,props)});app.config.errorHandler=e=>errors.push(e);app.config.warnHandler=e=>warnings.push(e);app.mount(root);await settle();assert.deepEqual(errors,[]);return{root,ssr:()=>renderToString(Vue.createSSRApp(component,props)),close(){app.unmount();assert.deepEqual(errors,[]);assert.deepEqual(warnings,[]);}};}
const button=(root,label)=>walk(root).find(el=>el.tag==='button'&&textOf(el)===label);
const show=o=>mount(modules.workspace.default,{workspace:o.h,assignments:o.assignments});

test('actual own workspace displays loaded history captured head facts and inert exact code self-report',async()=>{const o=owner();try{await o.h.refresh();await o.h.selectSubmission('submission-B');const v=await show(o);try{const text=textOf(v.root);assert.match(text,/我的提交历史|已加载 2|submission-B|123456|执行不可用（代码未执行）|评价尚未接入|学生自述/);assert.ok(text.includes(f.submission.content.text));assert.ok(text.includes(f.submission.ai_usage_declaration.description));assert.equal(walk(v.root).some(x=>['script','iframe','textarea','a'].includes(x.tag)),false);const ssr=await v.ssr();assert.ok(ssr.includes('&lt;script&gt;inert&lt;/script&gt;'));assert.doesNotMatch(ssr,/v-html|download=|运行代码|提交作业|待批改|分数|合规判定/);}finally{v.close();}}finally{o.close();}});
test('empty head says no received submission while head failure never becomes empty or zero',async()=>{for(const failure of [false,true]){const o=owner({api:apiFactory({getOwnHead:async()=>{if(failure)throw{status:503,reason:'invalid_assessment_state'};return clone(f.emptyHead);},listOwnHistory:async()=>({...clone(f.history),items:[],current_head_id:null})})});try{await o.h.refresh();const v=await show(o);try{assert.match(textOf(v.root),failure?/读取失败/:/尚无已接收提交/);if(failure)assert.doesNotMatch(textOf(v.root),/尚无已接收提交/);assert.doesNotMatch(textOf(v.root),/0 次提交/);}finally{v.close();}}finally{o.close();}}});
test('actual teacher exact selector form is access-gated local and preserves full subject',async()=>{const subject='😀'.repeat(247)+'/\\%?# 空格',calls=[];const o=owner({context:ctx({mode:'teaching',modes:['teaching'],roleScope:'offering',configuredPermissions:['SUBMISSION_VIEW']}),api:apiFactory({listTeacherSubmissions:async(_id,q)=>{calls.push(q);return clone(f.emptyTeacherHistory);}})});try{const v=await show(o);try{const input=walk(v.root).find(x=>x.tag==='input'&&x.props['aria-describedby']==='tw-subject-limit');assert.ok(input);assert.equal(input.props.maxlength,undefined,'HTML UTF-16 maxLength must not truncate exact code-point subject');assert.match(textOf(v.root),/精确学生标识|255|不查询名单|当前可见已提交记录/);input.props.onInput({target:{value:subject}});await settle();assert.equal(input.props.value,subject);button(v.root,'读取该学生历史').props.onClick({preventDefault(){}});await settle();assert.equal(calls.at(-1)?.studentId,subject,JSON.stringify({status:o.h.teacherHistory.status,error:o.h.teacherHistory.error,subject:o.h.studentId.value}));o.c.value=ctx({mode:'teaching',modes:['teaching'],roleScope:'offering',configuredPermissions:['RELEASE']});await settle();assert.equal(walk(v.root).some(x=>x.tag==='input'),false);}finally{v.close();}}finally{o.close();}});
test('visible teacher head row opens exact student history with no inferred names or roster',async()=>{const o=owner({context:ctx({mode:'teaching',modes:['teaching'],roleScope:'offering',configuredPermissions:['SUBMISSION_VIEW']})});try{await o.h.loadTeacherHeads();const v=await show(o);try{const buttons=walk(v.root).filter(x=>x.tag==='button'&&textOf(x)==='查看该学生历史');assert.equal(buttons.length,2);buttons[0].props.onClick();await settle();assert.equal(o.h.studentId.value,'student-A');assert.match(textOf(v.root),/student-A/);assert.doesNotMatch(textOf(v.root),/姓名|待批改|班级总数|未提交人数/);}finally{v.close();}}finally{o.close();}});
test('loaded row handler independently fetches detail and denial removes previous title body and cursor',async()=>{let deny=false;const o=owner({api:apiFactory({getRelease:async()=>{if(deny)throw{status:404,reason:'not_found'};return clone(f.release);}})});try{await o.h.refresh();const v=await show(o);try{walk(v.root).filter(x=>x.tag==='button'&&textOf(x)==='查看记录')[1].props.onClick();await settle();assert.ok(textOf(v.root).includes(f.submission.content.text));deny=true;await o.h.refresh();await settle();assert.doesNotMatch(textOf(v.root),/公开任务|print\(|学生声明|submission-B/);assert.equal(o.h.detail.data,null);}finally{v.close();}}finally{o.close();}});
test('failed next page visibly marks stale partial and disables row selection',async()=>{let n=0;const o=owner({api:apiFactory({listOwnHistory:async()=>{if(++n===1)return{...clone(f.history),items:[clone(f.first)],next_cursor:'AAAA'};throw{status:503,reason:'database_unavailable'};}})});try{await o.h.loadOwnHistory();await o.h.loadMore('ownHistory');const v=await show(o);try{assert.match(textOf(v.root),/已加载 1|数据可能已过期/);assert.ok(walk(v.root).filter(x=>x.tag==='button'&&textOf(x)==='查看记录').every(x=>x.props.disabled));}finally{v.close();}}finally{o.close();}});
test('main index shell wiring is source-only and read UI contains no mutation private feedback roster or runner',()=>{feature();const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');assert.match(read('js/main.js'),/teachingSubmissions:\s*teachingWorkbench.submissions/);assert.match(read('index.html'),/:submissions="teachingSubmissions"/);assert.match(read('js/components/teaching/TeachingWorkbenchShell.js'),/TeachingSubmissionReadWorkspace/);const source=['js/hooks/useTeachingSubmissions.js','js/components/teaching/SubmissionHistoryPanel.js','js/components/teaching/SubmissionFactsPanel.js','js/components/teaching/TeachingSubmissionReadWorkspace.js'].map(read).join('\n');assert.doesNotMatch(source,/v-html|innerHTML|\.listRoster|private-spec|private-draft|\/feedback|\.submit|\.publish|\.freeze|autosave|<textarea|download|createObjectURL/);const css=read('styles/teaching-workbench.css');for(const line of css.split('\n').filter(x=>x.includes('{')&&!x.includes('@container')))assert.ok(line.trim().startsWith('.teaching-workbench'),line);});

async function workbench({mode='learning',permissions=['SUBMISSION_VIEW'],hash='',changes={}}={}){feature();const calls=[],events=new Map(),location={hash,pathname:'/frontend/index.html',search:''};const auth={authVerified:Vue.ref(true),authEpoch:Vue.ref(1),currentUser:Vue.ref({username:'student-A'}),currentRole:Vue.ref('student'),currentView:Vue.ref('teaching-home')};const offering={id:'offering-A',course_id:'course-A',title:'实际课程',term:'秋季',timezone:'Asia/Shanghai',state:'active',enrollment:null,access:{teaching:mode==='teaching',learning:mode==='learning',role_scope:mode==='teaching'?'offering':null,configured_permissions:permissions,writes_available:false,available_actions:[]}};const api={getCapabilities:async()=>({account_role:'student',configured:true,available:true,reason:'available',assignments:{configured:true,installed:true,available:true,reason:'read_ready'}}),listCourses:async()=>({items:[],next_cursor:null,as_of:at}),listOfferings:async()=>({items:[offering],next_cursor:null,as_of:at}),getOffering:async()=>offering,getEnrollment:async()=>({id:'enrollment-A',offering_id:'offering-A',student_id:'student-A',status:'active',revision:1,access_eligible:true,effective_from:at,effective_until:null}),listRoster:async()=>{throw Error('No roster');}};const assignmentApi={listReleases:async()=>{calls.push('releases');return{items:[clone(f.release)],next_cursor:null,as_of:at};},getRelease:async()=>{calls.push('release');return clone(f.release);},...apiFactory(),...changes};for(const k of ['getOwnHead','listOwnHistory','listTeacherSubmissions','getSubmission']){const fn=assignmentApi[k];assignmentApi[k]=(...args)=>{calls.push(k);return fn(...args);};}let h;const app=renderer.createApp({setup(){h=modules.workbench.useTeachingWorkbench(auth,async view=>{auth.currentView.value=view;return true;},{api,assignmentApi,location,history:{replaceState:(_a,_b,url)=>location.hash=url.includes('#')?url.slice(url.indexOf('#')):''},eventTarget:{addEventListener:(k,v)=>events.set(k,v),removeEventListener:k=>events.delete(k)},locatorStore:null});return()=>null;}});app.mount(node('root'));await settle();return{h,auth,calls,location,events,close:()=>app.unmount()};}
test('mounted guarded history lists releases then opens own history with fresh ancestry and no teacher route',async()=>{const o=await workbench();try{await o.h.selectOffering('offering-A');await o.h.openSection('history');assert.equal(o.h.assignments.assignmentPage.items.length,0);assert.equal(await o.h.submissionNavigation.selectRelease('release-A'),true);assert.equal(o.h.submissions.ownHistory.items.length,2);assert.ok(o.calls.includes('getOwnHead'));assert.equal(o.calls.includes('listTeacherSubmissions'),false);assert.equal(await o.h.submissionNavigation.selectSubmission('submission-B'),true);assert.equal(o.location.hash,'#teaching/offerings/offering-A/releases/release-A/submissions/submission-B');assert.equal(o.h.locationUnavailable.value,false);}finally{o.close();}});
test('supported initial detail locator installs release and returned history before any detail request',async()=>{const o=await workbench({hash:'#teaching/offerings/offering-A/releases/release-A/submissions/submission-B'});try{await settle();assert.equal(o.h.locationUnavailable.value,false);assert.equal(o.h.submissions.detail.data?.id,'submission-B');assert.ok(o.calls.indexOf('listOwnHistory')<o.calls.indexOf('getSubmission'));}finally{o.close();}});
test('uninstalled initial submission locator stays generic and never probes detail',async()=>{const o=await workbench({hash:'#teaching/offerings/offering-A/releases/release-A/submissions/unknown'});try{await settle();assert.equal(o.h.locationUnavailable.value,true);assert.equal(o.calls.includes('getSubmission'),false);}finally{o.close();}});
test('current denial in mounted history clears B public title and all C content and shows generic unavailable',async()=>{let deny=false;const o=await workbench({changes:{getRelease:async()=>{if(deny)throw{status:403,reason:'permission_denied'};return clone(f.release);}}});try{await o.h.selectOffering('offering-A');await o.h.openSection('history');await o.h.submissionNavigation.selectRelease('release-A');await o.h.submissions.selectSubmission('submission-B');deny=true;await o.h.submissions.loadOwnHistory();assert.equal(o.h.assignments.release.data,null);assert.equal(o.h.assignments.releasePage.items.length,0);assert.equal(o.h.locationUnavailable.value,true);assert.equal(o.h.submissions.detail.data,null);}finally{o.close();}});
test('teacher without SUBMISSION_VIEW has no selector request even with release access',async()=>{const o=await workbench({mode:'teaching',permissions:['RELEASE']});try{await o.h.selectOffering('offering-A');await o.h.openSection('history');assert.equal(await o.h.submissions.loadTeacherHistory('student-A'),false);assert.equal(o.calls.includes('listTeacherSubmissions'),false);assert.equal(o.calls.includes('getSubmission'),false);}finally{o.close();}});

test('editing exact selector synchronously removes previous subject history detail and cursor before request',async()=>{let calls=0;const o=owner({context:ctx({mode:'teaching',modes:['teaching'],roleScope:'offering',configuredPermissions:['SUBMISSION_VIEW']}),api:apiFactory({listTeacherSubmissions:async()=>{calls++;return{...clone(f.teacherHistory),next_cursor:'AAAA'};}})});try{await o.h.loadTeacherHistory('student-A');await o.h.selectSubmission('submission-B');const v=await show(o);try{const input=walk(v.root).find(x=>x.tag==='input'&&x.props['aria-describedby']==='tw-subject-limit');input.props.onInput({target:{value:'other'}});assert.equal(o.h.teacherHistory.items.length,0);assert.equal(o.h.teacherHistory.nextCursor,null);assert.equal(o.h.detail.data,null);assert.equal(o.h.studentId.value,null);assert.equal(calls,1);}finally{v.close();}}finally{o.close();}});

test('accepted nullable head retains its own precise read time separately from empty history time',async()=>{
 const o=owner({api:apiFactory({getOwnHead:async()=>clone(f.emptyHead),listOwnHistory:async()=>({items:[],current_head_id:null,next_cursor:null,as_of:'2026-10-04T04:31:00.654321Z'})})});
 try{await o.h.refresh();const v=await show(o);try{assert.ok(textOf(v.root).includes('头读取时点 '+at));assert.ok(textOf(v.root).includes('2026-10-04T04:31:00.654321Z'));}finally{v.close();}}finally{o.close();}
});

test('actual mounted shell history seam shows authorized own records and inert detail through workbench wiring',async()=>{
 const o=await workbench();try{await o.h.selectOffering('offering-A');await o.h.openSection('history');await o.h.submissionNavigation.selectRelease('release-A');await o.h.submissionNavigation.selectSubmission('submission-B');
  const props={context:o.h.context.value,accessMode:o.h.context.value.mode,section:'history',courses:o.h.courses,offerings:o.h.offerings,offering:o.h.offering,enrollment:o.h.enrollment,availability:o.h.availability.value,assignments:o.h.assignments,submissions:o.h.submissions,submissionNavigation:o.h.submissionNavigation,locationUnavailable:o.h.locationUnavailable.value,tools:[]};
  const v=await mount(modules.shell.default,props);try{assert.ok(textOf(v.root).includes('我的提交历史'));assert.ok(textOf(v.root).includes(f.submission.content.text));assert.doesNotMatch(textOf(v.root),/提交记录读取界面尚未接入/);assert.ok((await v.ssr()).includes('&lt;script&gt;inert&lt;/script&gt;'));}finally{v.close();}
 }finally{o.close();}
});
test('teacher initial current-head locator installs exact head subject and allows own-priority detail without fabricated student field',async()=>{
 const o=await workbench({mode:'teaching',hash:'#teaching/offerings/offering-A/releases/release-A/submissions/submission-B'});
 try{await settle();assert.equal(o.h.locationUnavailable.value,false);assert.equal(o.h.submissions.detail.data?.id,'submission-B');assert.equal(Object.hasOwn(o.h.submissions.detail.data,'student_id'),false);assert.ok(o.calls.indexOf('listTeacherSubmissions')<o.calls.indexOf('getSubmission'));assert.equal(o.calls.includes('listOwnHistory'),false);}finally{o.close();}
});
test('teacher initial historic detail without exact locally selected subject remains generic and never guesses a student',async()=>{
 const o=await workbench({mode:'teaching',hash:'#teaching/offerings/offering-A/releases/release-A/submissions/submission-A'});
 try{await settle();assert.equal(o.h.locationUnavailable.value,true);assert.equal(o.calls.includes('getSubmission'),false);assert.equal(o.h.submissions.studentId.value,null);assert.equal(o.h.submissions.detail.data,null);}finally{o.close();}
});
