import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { Vue,mount,find,walk,button,textOf,settle,documentFor,compiled,source } from './fixtures/workPresentationRenderer.mjs';
const detailURL=new URL('../js/components/WorkPaperDetail.js',import.meta.url),hookURL=new URL('../js/hooks/useWorkPresentation.js',import.meta.url);
const Detail=existsSync(detailURL)?(await import(detailURL)).default:null,hook=existsSync(hookURL)?await import(hookURL):null;
const record={id:'A',title:'actual A',authorsText:'Actual Author',year:2024,venue:'Actual Venue',doi:'10.1000/test',arxivId:'2401.00001',pmid:'123',abstract:'Provided abstract',retrievedAt:'2026-10-04',citationCount:0,citationCountSource:'Crossref',sources:[{key:'crossref',label:'Crossref',recordId:'source-123'}],officialUrl:'https://doi.org/10.1000/test',openAccessUrl:'https://example.org/actual'};
test('shared detail pane and modal expose truthful metadata and exact single-paper action payloads',async()=>{assert.ok(Detail,'Shared detail component must be installed');for(const presentation of ['pane','modal']){const h=await mount(Detail,{paper:record,presentation});try{for(const text of ['Actual Author','Actual Venue','10.1000/test','2401.00001','123','2026-10-04','Crossref','source-123','Provided abstract','未读取全文'])assert.ok(textOf(h.root).includes(text),text);for(const [label,event,args] of [['复制 BibTeX','copy-citation',[]],['下载 .bib','download-citation',['bib']],['下载 .ris','download-citation',['ris']],['引入对话','insert-to-chat',[]],['关闭详情','close',[]]]){button(h.root,label).props.onClick();assert.deepEqual(h.emitted[event].at(-1),args);}assert.equal(find(h.root,el=>el.props['data-work-detail-heading']!==undefined).props.tabindex,'-1');assert.equal(find(h.root,el=>el.props.role===(presentation==='modal'?'dialog':'region')).props['aria-modal'],presentation==='modal'?true:undefined);assert.deepEqual(record.sources,[{key:'crossref',label:'Crossref',recordId:'source-123'}]);}finally{h.close();}}});
test('missing abstract identifiers and unsafe links stay plain truthful content',async()=>{assert.ok(Detail,'Shared detail component must be installed');for(const officialUrl of ['javascript:alert(1)','data:text/html,<script>','https://user:password@example.org','']){const title='<img src=x onerror=alert(1)> '+('long title '.repeat(90)),h=await mount(Detail,{paper:{title,officialUrl,openAccessUrl:'javascript:alert(2)'},presentation:'pane'});try{assert.ok(textOf(h.root).includes(title));assert.equal(walk(h.root).filter(el=>['img','script'].includes(el.tag)).length,0);assert.equal(walk(h.root).filter(el=>el.tag==='a').length,0);assert.match(textOf(h.root),/未提供摘要|暂无官方标识符|未读取全文/);assert.doesNotMatch(textOf(h.root),/开放学术元数据/);}finally{h.close();}}});
test('select A then B focuses installed detail and close restores surviving exact trigger',async()=>{assert.ok(Detail&&hook,'Detail and presentation hook must be installed');const selected=Vue.ref(null),modal=Vue.ref(false);let presentation;const h=await mount({components:{WorkPaperDetail:compiled(Detail)},template:'<div><button id="A" @click="openWorkPaperDetail(A, $event)">A</button><button id="B" @click="openWorkPaperDetail(B, $event)">B</button><WorkPaperDetail v-if="selectedPaper" :paper="selectedPaper" :presentation="modal ? \'modal\' : \'pane\'" @close="closeWorkPaperDetail" /><textarea data-work-dialog-composer></textarea></div>',setup(){presentation=hook.useWorkPresentation({selectedPaper:selected,isDetailVisible:()=>Boolean(selected.value),openPaperDetail:p=>selected.value=p,closePaperDetail:()=>selected.value=null,insertPaperToChat:()=>selected.value=null,returnToChatDialog(){}});return{...presentation,selectedPaper:selected,modal,A:record,B:{...record,id:'B',title:'actual B'}};}});documentFor(h.root);try{for(const id of ['A','B']){const trigger=find(h.root,el=>el.props.id===id);trigger.props.onClick({currentTarget:trigger});await settle();assert.equal(selected.value.id,id);assert.equal(document.activeElement.props['data-work-detail-heading'],'');}assert.match(textOf(h.root),/actual B/);button(h.root,'关闭详情').props.onClick();await settle();assert.equal(selected.value,null);assert.equal(document.activeElement.props.id,'B');}finally{h.close();}});
test('modal Escape close and Tab trap use native handlers and never claim pane modality',async()=>{assert.ok(Detail,'Shared detail component must be installed');const h=await mount(Detail,{paper:record,presentation:'modal'});documentFor(h.root);try{const root=find(h.root,el=>el.props.role==='dialog');let prevented=0;const controls=walk(root).filter(el=>['button','a'].includes(el.tag));root.querySelectorAll=()=>controls;document.activeElement=controls.at(-1);root.props.onKeydown({key:'Tab',currentTarget:root,shiftKey:false,preventDefault(){prevented++;}});assert.equal(document.activeElement,controls[0]);assert.equal(prevented,1);root.props.onKeydown({key:'Escape',preventDefault(){},stopPropagation(){}});assert.deepEqual(h.emitted.close,[[]]);}finally{h.close();}});
test('import closes detail switches same paper task and focuses installed dialog composer',async()=>{assert.ok(hook,'Presentation hook must be installed');const selected=Vue.ref(record),task=Vue.ref('same-task'),tab=Vue.ref('results'),draft=Vue.ref('existing draft');let presentation;const h=await mount({template:'<div><button @click="insertWorkPaperToChat(paper)">Import</button><textarea v-if="tab === \'dialog\'" data-work-dialog-composer></textarea></div>',setup(){presentation=hook.useWorkPresentation({selectedPaper:selected,isDetailVisible:()=>tab.value==='results'&&Boolean(selected.value),insertPaperToChat:paper=>{draft.value+=' '+paper.abstract;selected.value=null;},returnToChatDialog:()=>tab.value='dialog'});return{...presentation,paper:record,tab};}});documentFor(h.root);try{button(h.root,'Import').props.onClick();await settle();assert.equal(selected.value,null);assert.equal(task.value,'same-task');assert.equal(tab.value,'dialog');assert.match(draft.value,/existing draft Provided abstract/);assert.equal(document.activeElement.props['data-work-dialog-composer'],'');}finally{h.close();}});

test('installed Work pane and plugin fallback are mutually exclusive with an honest empty pane',async()=>{assert.ok(Detail&&hook);const html=source('index.html'),paneStart=html.indexOf('<aside class="work-detail-pane"'),paneEnd=html.indexOf('</aside>',paneStart)+8,modalStart=html.indexOf('<div v-if="selectedPaper && activeSearchPlugin"'),modalEnd=html.indexOf('</transition>',modalStart);const selected=Vue.ref(null),plugin=Vue.ref(null),view=Vue.ref('workspace'),mode=Vue.ref('paper'),tab=Vue.ref('results');const template='<div><main v-if="currentView === \'workspace\' && agentMode === \'paper\' && paperActiveTab === \'results\'">'+html.slice(paneStart,paneEnd)+'</main>'+html.slice(modalStart,modalEnd)+'</div>';const h=await mount({components:{WorkPaperDetail:compiled(Detail)},template,setup(){return{selectedPaper:selected,activeSearchPlugin:plugin,currentView:view,agentMode:mode,paperActiveTab:tab,closePaperDetail:()=>selected.value=null,copyPaperCitation(){},downloadPaperCitation(){},insertPaperToChat(){}};}});try{assert.match(textOf(h.root),/选择文献查看详情/);assert.equal(walk(h.root).filter(el=>el.props.role==='region'||el.props.role==='dialog').length,0);selected.value=record;await settle();assert.equal(walk(h.root).filter(el=>el.props.role==='region').length,1);assert.equal(walk(h.root).filter(el=>el.props.role==='dialog').length,0);plugin.value={id:'selected-source'};await settle();assert.equal(walk(h.root).filter(el=>el.props.role==='region').length,0);assert.equal(walk(h.root).filter(el=>el.props.role==='dialog').length,1);find(h.root,el=>el.props.class==='work-detail-modal-backdrop').props.onClick({target:null,currentTarget:null});await settle();assert.equal(selected.value,null);plugin.value=null;selected.value=record;view.value='dashboard';await settle();assert.equal(walk(h.root).filter(el=>el.props.role==='dialog'||el.props.role==='region').length,0);view.value='workspace';tab.value='dialog';await settle();assert.equal(walk(h.root).filter(el=>el.props.role==='dialog'||el.props.role==='region').length,0);}finally{h.close();}});

test('selection invalidated before mount never focuses an old or hidden Work detail',async()=>{assert.ok(hook);const selected=Vue.ref(null),visible=Vue.ref(true);let state,focuses=0;const target={isConnected:true,focus(){focuses++;}};globalThis.document={activeElement:null,querySelector:()=>target};const scope=Vue.effectScope();try{state=scope.run(()=>hook.useWorkPresentation({selectedPaper:selected,isDetailVisible:()=>visible.value,openPaperDetail:p=>selected.value=p,closePaperDetail:()=>selected.value=null}));const pending=state.openWorkPaperDetail(record,{currentTarget:target});visible.value=false;await pending;assert.equal(focuses,0);visible.value=true;const next=state.openWorkPaperDetail(record,{currentTarget:target});selected.value=null;await next;assert.equal(focuses,0);const opening=state.openWorkPaperDetail(record,{currentTarget:target});await opening;assert.equal(focuses,1);target.isConnected=false;await state.closeWorkPaperDetail();assert.equal(focuses,1);}finally{scope.stop();}});
test('modal initial heading Shift Tab stays inside the installed dialog',async()=>{assert.ok(Detail);const h=await mount(Detail,{paper:record,presentation:'modal'});documentFor(h.root);try{const root=find(h.root,el=>el.props.role==='dialog'),controls=walk(root).filter(el=>['button','a'].includes(el.tag)),heading=find(h.root,el=>el.props['data-work-detail-heading']!==undefined);root.querySelectorAll=()=>controls;heading.focus();let prevented=false;root.props.onKeydown({key:'Tab',currentTarget:root,shiftKey:true,preventDefault(){prevented=true;}});assert.equal(prevented,true);assert.equal(document.activeElement,controls.at(-1));}finally{h.close();}});
test('installed detail citation and import events execute real existing hooks for one selected paper',async()=>{
    const {usePlugins}=await import('../js/hooks/usePlugins.js');
    const {useChat}=await import('../js/hooks/useChat.js');
    localStorage.clear();globalThis.window={location:{hostname:'frontend.invalid'},addEventListener(){},removeEventListener(){},dispatchEvent(){}};
    globalThis.fetch=async()=>({ok:true,text:async()=>JSON.stringify({status:'success',data:[]})});
    const scope=Vue.effectScope(),user=Vue.ref(null),chat=scope.run(()=>useChat(user,()=>{})),plugins=scope.run(()=>usePlugins(user,()=>{},chat.inputText));
    chat.agentMode.value='paper';chat.activeConversationId.value='same-paper-task';chat.inputText.value='preserved draft';plugins.selectedPaper.value=record;
    chat.setWorkspaceCancellationHandler(plugins.cancelPaperSearch);
    const html=source('index.html'),a=html.indexOf('<aside class="work-detail-pane"'),b=html.indexOf('</aside>',a)+8;
    const h=await mount({components:{WorkPaperDetail:compiled(Detail)},template:'<div>'+html.slice(a,b)+'<textarea v-if="paperActiveTab === \'dialog\'" data-work-dialog-composer></textarea></div>',setup(){const state=hook.useWorkPresentation({selectedPaper:plugins.selectedPaper,isDetailVisible:()=>chat.paperActiveTab.value==='results',openPaperDetail:plugins.openPaperDetail,closePaperDetail:plugins.closePaperDetail,insertPaperToChat:plugins.insertPaperToChat,returnToChatDialog:chat.returnToChatDialog});return{selectedPaper:plugins.selectedPaper,activeSearchPlugin:plugins.activeSearchPlugin,paperActiveTab:chat.paperActiveTab,closePaperDetail:state.closeWorkPaperDetail,copyPaperCitation:plugins.copyPaperCitation,downloadPaperCitation:plugins.downloadPaperCitation,insertPaperToChat:state.insertWorkPaperToChat};}});
    documentFor(h.root);let copied='',downloads=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>copied=text},configurable:true});
    let completeDownloads,removedDownloads=0;const downloadsFinished=new Promise(resolve=>completeDownloads=resolve);
    const blobs=[],createURL=URL.createObjectURL;URL.createObjectURL=blob=>{blobs.push(blob);return createURL(blob);};document.body={appendChild(){},removeChild(){if(++removedDownloads===2)completeDownloads();}};document.createElement=()=>({style:{},click(){downloads.push(this.download);}});
    try{button(h.root,'复制 BibTeX').props.onClick();await settle();assert.match(copied,/title = \{actual A\}/);button(h.root,'下载 .bib').props.onClick();button(h.root,'下载 .ris').props.onClick();assert.equal(downloads.length,2);assert.ok(downloads[0].endsWith('.bib'));assert.ok(downloads[1].endsWith('.ris'));assert.match(await blobs[0].text(),/actual A/);assert.match(await blobs[1].text(),/TI  - actual A/);button(h.root,'引入对话').props.onClick();await settle();assert.equal(chat.activeConversationId.value,'same-paper-task');assert.equal(chat.agentMode.value,'paper');assert.equal(chat.paperActiveTab.value,'dialog');assert.equal(plugins.selectedPaper.value,null);assert.match(chat.inputText.value,/preserved draft/);assert.match(chat.inputText.value,/Provided abstract/);assert.match(chat.inputText.value,/未读取全文/);assert.equal(document.activeElement.props['data-work-dialog-composer'],'');await downloadsFinished;}
    finally{URL.createObjectURL=createURL;h.close();scope.stop();}
});
test('native close A then open B before settling preserves B return focus on its later close',async()=>{
    const selected=Vue.ref(null);const h=await mount({components:{WorkPaperDetail:compiled(Detail)},template:'<div><button id="A" @click="openWorkPaperDetail(A, $event)">A</button><button id="B" @click="openWorkPaperDetail(B, $event)">B</button><WorkPaperDetail v-if="selectedPaper" :paper="selectedPaper" presentation="pane" @close="closeWorkPaperDetail" /></div>',setup(){return{...hook.useWorkPresentation({selectedPaper:selected,isDetailVisible:()=>Boolean(selected.value),openPaperDetail:paper=>selected.value=paper,closePaperDetail:()=>selected.value=null}),selectedPaper:selected,A:record,B:{...record,id:'B',title:'actual B'}};}});documentFor(h.root);
    try{const triggerA=find(h.root,el=>el.props.id==='A'),triggerB=find(h.root,el=>el.props.id==='B');triggerA.props.onClick({currentTarget:triggerA});await settle();button(h.root,'关闭详情').props.onClick();triggerB.props.onClick({currentTarget:triggerB});await settle();assert.equal(selected.value.id,'B');assert.equal(document.activeElement.props['data-work-detail-heading'],'');button(h.root,'关闭详情').props.onClick();await settle();assert.equal(selected.value,null);assert.equal(document.activeElement,triggerB);}
    finally{h.close();}
});
