import test from 'node:test';
import { withCapabilities, capabilityFixture } from './support/studentWorkCapabilitiesFixture.mjs';
import { parseStudentWorkCapabilities } from '../js/utils/studentWorkCapabilities.js';
const capabilityFacts = parseStudentWorkCapabilities(capabilityFixture());
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { Vue, source, mount, walk, find, button, settle, textOf, documentFor } from './fixtures/workPresentationRenderer.mjs';
const {usePlugins}=await import('../js/hooks/usePlugins.js');
const {useChat}=await import('../js/hooks/useChat.js');
const {useStudentNavigationPresentation}=await import('../js/hooks/useStudentNavigationPresentation.js');
const {createWorkspaceMessageSender}=await import('../js/controllers/workspaceSendRouter.js');
const presentationURL=new URL('../js/hooks/useWorkPresentation.js',import.meta.url);
const presentation=existsSync(presentationURL)?await import(presentationURL):null;
function environment(){localStorage.clear();globalThis.window={location:{hostname:'frontend.invalid'},addEventListener(){},removeEventListener(){},dispatchEvent(){}};globalThis.document={querySelector:()=>null};globalThis.fetch=withCapabilities(async()=>({ok:true,text:async()=>JSON.stringify({status:'success',data:[]})}));}
function hooks(){environment();const scope=Vue.effectScope(),user=Vue.ref(null),draft=Vue.ref('draft');const plugins=scope.run(()=>usePlugins(user,()=>{},draft)),chat=scope.run(()=>useChat(user,()=>{}));return{scope,user,plugins,chat};}
function slice(html,start,end){const a=html.indexOf(start);assert.ok(a>=0,'Installed markup '+start);const b=html.indexOf(end,a);assert.ok(b>a);return html.slice(a,b);}
test('new empty and no-source searches clear an explicitly selected older paper before validation',async()=>{const h=hooks();try{h.plugins.installedPluginIds.value=[];for(const query of ['', 'new topic']){h.plugins.openPaperDetail({id:'old',title:'old result'});assert.equal(await h.plugins.executePaperSearch(query),false);assert.equal(h.plugins.selectedPaper.value,null);assert.equal(h.plugins.isSearchingPapers.value,false);}}finally{h.scope.stop();}});
test('independent Work and global collapses preserve live task mode draft results and transcript',async()=>{assert.ok(presentation,'Work presentation hook must be installed');const h=hooks();try{const role=Vue.ref('student'),nav=h.scope.run(()=>useStudentNavigationPresentation(role)),work=h.scope.run(()=>presentation.useWorkPresentation());h.chat.agentMode.value='paper';h.chat.activeConversationId.value='task-live';h.chat.inputText.value='unsent question';h.chat.modeMessageBuckets.value.paper=[{id:'m',conversationId:'task-live',content:'transcript',mode:'paper',senderType:'user'}];h.plugins.paperSearchResults.value=[{id:'p',title:'actual record'}];const before=JSON.stringify([h.chat.activeConversationId.value,h.chat.agentMode.value,h.chat.inputText.value,h.chat.modeMessageBuckets.value,h.plugins.paperSearchResults.value]);for(const global of [false,true])for(const rail of [false,true]){nav.studentNavCollapsed.value=global;if(work.workTaskRailCollapsed.value!==rail)work.toggleWorkTaskRail();assert.equal(nav.studentNavCollapsed.value,global);assert.equal(work.workTaskRailCollapsed.value,rail);assert.equal(JSON.stringify([h.chat.activeConversationId.value,h.chat.agentMode.value,h.chat.inputText.value,h.chat.modeMessageBuckets.value,h.plugins.paperSearchResults.value]),before);}}finally{h.scope.stop();}});
test('compiled persistent task toggle focuses reopen control and only changes presentation',async()=>{assert.ok(presentation,'Work presentation hook must be installed');const html=source('index.html'),template=slice(html,'<button id="work-taskrail-toggle"','</button>')+'</button>';let state;const h=await mount({template,setup(){state=presentation.useWorkPresentation();return state;}});try{documentFor(h.root);const control=find(h.root,el=>el.tag==='button');control.props.onClick({currentTarget:control});await settle();assert.equal(control.props['aria-expanded'],false);assert.equal(control.props['aria-controls'],'work-taskrail');assert.match(textOf(control),/展开任务栏/);assert.equal(document.activeElement,control);control.props.onClick({currentTarget:control});await settle();assert.equal(control.props['aria-expanded'],true);assert.match(textOf(control),/收起任务栏/);}finally{h.close();}});
test('compiled horizontal mode controls invoke the existing switch handler exactly once',async()=>{environment();const html=source('index.html'),template=slice(html,'<nav class="work-mode-tabs"','</nav>')+'</nav>',scope=Vue.effectScope(),chat=scope.run(()=>useChat(Vue.ref(null),()=>{})),calls=[];assert.equal(chat.agentMode.value,'tutor');const h=await mount({template,setup(){return{agentMode:chat.agentMode,switchWorkMode(mode){calls.push(mode);chat.switchWorkMode(mode);}};}});try{for(const mode of ['chat','rag','tutor','paper']){find(h.root,el=>el.props.id==='btn-switch-mode-'+mode).props.onClick();await settle();assert.equal(calls.filter(value=>value===mode).length,1);assert.equal(chat.agentMode.value,mode);assert.equal(find(h.root,el=>el.props.id==='btn-switch-mode-'+mode).props['aria-pressed'],true);}}finally{h.close();scope.stop();}});
test('compiled paper query and Enter use results search while dialog remains existing chat routing',async()=>{const h=hooks(),calls=[],html=source('index.html');h.chat.agentMode.value='paper';h.chat.inputText.value='actual query';const send=createWorkspaceMessageSender({getMode:()=>h.chat.agentMode.value,getInput:()=>h.chat.inputText.value,getPaperTab:()=>h.chat.paperActiveTab.value,searchPapers:async query=>{calls.push(['search',query]);return false;},sendChat:async query=>{calls.push(['chat',query]);return true;}});const view=await mount({template:slice(html,'<form class="work-paper-query"','</form>')+'</form>',setup(){return{agentMode:h.chat.agentMode,inputText:h.chat.inputText,isSearchingPapers:h.plugins.isSearchingPapers,thinkingAgent:h.chat.thinkingAgent,sendMessage:send,installedPlugins:h.plugins.installedPlugins,activeInputPlugins:h.plugins.activeInputPlugins,removeActiveInputPlugin:h.plugins.removeActiveInputPlugin,openPluginMarket:h.plugins.openPluginMarket};}});try{const form=find(view.root,el=>el.tag==='form');await form.props.onSubmit({preventDefault(){}});assert.deepEqual(calls,[['search','actual query']]);const field=find(view.root,el=>el.tag==='input');await field.props.onKeydown({key:'Enter',preventDefault(){},shiftKey:false,ctrlKey:false,altKey:false,metaKey:false});assert.equal(calls.length,2);h.chat.returnToChatDialog();assert.equal(h.chat.paperActiveTab.value,'dialog');assert.equal(h.chat.agentMode.value,'paper');await send();assert.deepEqual(calls.at(-1),['chat','actual query']);h.plugins.isSearchingPapers.value=true;await settle();assert.equal(button(view.root,'查询论文').props.disabled,true);}finally{view.close();h.scope.stop();}});
test('compiled results retain bounded statuses receipts retry and dynamic sources',async()=>{const h=hooks(),html=source('index.html');const template=slice(html,'<div class="work-paper-results"','<!-- Work detail pane -->');const retries=[];const view=await mount({template,setup(){return{agentMode:h.chat.agentMode,paperWorkSyncStatus:Vue.ref({state:'failed',error:'offline',conversationId:'t'}),retryPaperWorkSync:id=>retries.push(id),...h.plugins,returnToChatDialog:h.chat.returnToChatDialog,sendMessage(){},inputText:h.chat.inputText,Math};}});try{for(const status of ['searching','partial','empty','error','cancelled']){h.plugins.paperSearchStatus.value=status;h.plugins.paperSearchError.value='actual error';await settle();assert.match(textOf(view.root),new RegExp({searching:'正在检索',partial:'部分来源不可用',empty:'未找到匹配论文',error:'检索失败',cancelled:'已取消'}[status]));}button(view.root,'重试同步').props.onClick();assert.deepEqual(retries,['t']);h.plugins.paperSourceStatuses.value=[{key:'crossref',label:'Crossref',status:'success',count:2,durationMs:4}];h.plugins.paperSearchResults.value=[{id:'p',title:'actual record',sources:[]}];h.plugins.paperSearchSummary.value={totalFetched:7,totalRejected:1,totalAfterMerge:6,snapshotComplete:false};await settle();assert.match(textOf(view.root),/来源返回 7 条，剔除无效标题 1 条，去重后 6 篇/);assert.match(textOf(view.root),/当前展示 1 篇/);assert.match(textOf(view.root),/1 \/ 6/);assert.match(textOf(view.root),/Crossref/);assert.doesNotMatch(textOf(view.root),/Europe PMC/);}finally{view.close();h.scope.stop();}});
test('integration mounts one detail modality and keeps existing non-paper composer and tutor guide',()=>{assert.ok(existsSync(new URL('../styles/workspace-light.css',import.meta.url)),'Scoped Work CSS must be installed');const html=source('index.html'),main=source('js/main.js'),css=source('styles/workspace-light.css');assert.match(html,/v-if="selectedPaper && activeSearchPlugin"/);assert.match(html,/v-if="selectedPaper && !activeSearchPlugin"/);assert.match(html,/选择文献查看详情/);assert.match(html,/data-work-dialog-composer/);assert.match(html,/ref="chatContainer"/);assert.match(html,/visualGuide/);assert.match(main,/useWorkPresentation/);assert.match(main,/WorkPaperDetail/);for(const id of ['header-return-to-chat-btn','status-return-to-chat-btn','bottom-return-to-chat-btn'])assert.match(html,new RegExp(id));assert.match(css,/min-width:\s*0/);assert.match(css,/\.work-light/);assert.doesNotMatch(css,/@media[^\{]*max-width:\s*[1-9]\d{0,2}px/);});

test('complete installed Work template compiles without missing tags or duplicate attributes',()=>{const html=source('index.html'),a=html.indexOf(`<div v-show="currentView === 'workspace'"`),b=html.lastIndexOf('</transition>',html.indexOf('<!-- 自定义大模型配置弹窗',a));assert.ok(a>0&&b>a);Vue.compile(html.slice(a,b),{hoistStatic:false,onError(error){throw error;},decodeEntities:raw=>raw});});

test('actual main history selection restores an older snapshot bounded counts and current task highlight',async()=>{const h=hooks();const {resolvePaperHistoryState}=await import('../js/utils/conversations.js');try{h.chat.agentMode.value='paper';h.chat.modeMessageBuckets.value.paper=[{id:'older-msg',senderType:'agent',mode:'paper',conversationId:'older-task',projectId:'proj-paper',content:'old transcript',paperSearchSnapshot:{query:'older actual query',status:'partial',results:[{id:'old-paper',title:'old actual title'}],summary:{totalFetched:8,totalRejected:1,totalAfterMerge:7,snapshotComplete:false}}},{id:'newer-msg',senderType:'user',mode:'paper',conversationId:'newer-task',content:'new transcript'}];h.chat.activeConversationId.value='newer-task';h.plugins.openPaperDetail({id:'stale',title:'stale'});const main=source('js/main.js'),a=main.indexOf('const restoreActivePaperTask ='),b=main.indexOf('const handleBackToCurrentConversation =',a);assert.ok(a>=0&&b>a);const handlers=new Function('chat','pluginsState','resolvePaperHistoryState',main.slice(a,b)+';return {handleSelectConversation};')(h.chat,h.plugins,resolvePaperHistoryState);await handlers.handleSelectConversation('older-task');assert.equal(h.chat.activeConversationId.value,'older-task');assert.equal(h.chat.sidebarActiveConversationId.value,'older-task');assert.equal(h.plugins.paperSearchQuery.value,'older actual query');assert.equal(h.plugins.paperSearchResults.value.length,1);assert.equal(h.plugins.paperSearchSummary.value.totalAfterMerge,7);assert.equal(h.plugins.paperSearchSummary.value.snapshotComplete,false);assert.equal(h.plugins.selectedPaper.value,null);assert.equal(h.chat.activeConversationMessages.value[0].content,'old transcript');}finally{h.scope.stop();}});

test('compiled global and Work task rails support all four visible layouts without resetting active state',async()=>{assert.ok(presentation);const h=hooks(),html=source('index.html'),navStart=html.indexOf('<nav id="legacy-global-navigation"'),navEnd=html.indexOf('</nav>',navStart)+6,rootStart=html.indexOf(`<div v-show="currentView === 'workspace'"`),rootEnd=html.indexOf('>',rootStart)+1,railStart=html.indexOf('<aside id="work-taskrail"',rootStart),railEnd=html.indexOf('</aside>',railStart)+8,toggleStart=html.indexOf('<button id="work-taskrail-toggle"',railEnd),toggleEnd=html.indexOf('</button>',toggleStart)+9;const role=Vue.ref('student'),view=Vue.ref('workspace'),nav=h.scope.run(()=>useStudentNavigationPresentation(role)),work=h.scope.run(()=>presentation.useWorkPresentation());h.chat.agentMode.value='paper';h.chat.activeConversationId.value='live-task';h.chat.inputText.value='still unsent';h.chat.modeMessageBuckets.value.paper=[{id:'msg',mode:'paper',conversationId:'live-task',content:'actual transcript',senderType:'user'}];h.plugins.paperSearchResults.value=[{id:'p',title:'actual paper'}];const template='<div>'+html.slice(navStart,navEnd)+html.slice(rootStart,rootEnd)+html.slice(railStart,railEnd)+html.slice(toggleStart,toggleEnd)+'</div></div>';const mounted=await mount({template,setup(){return{...h.chat,...h.plugins,...nav,...work,currentRole:role,currentView:view,currentUser:{username:'synthetic'},activeMenus:[{id:'workspace',name:'一站式 Work',icon:'ph-article'}],openUserCenter(){},handleLogout(){},isCreatingProject:Vue.ref(false),newProjectTitle:Vue.ref(''),submitCreateProject(){},openCustomModelModal(){},userCustomConfigs:[],showToast(){}};}});documentFor(mounted.root);try{const before=JSON.stringify([h.chat.activeConversationId.value,h.chat.agentMode.value,h.chat.inputText.value,h.chat.modeMessageBuckets.value,h.plugins.paperSearchResults.value]);for(const collapsed of [false,true])for(const railCollapsed of [false,true]){const globalToggle=find(mounted.root,el=>el.props['aria-controls']==='legacy-global-navigation');if(nav.studentNavCollapsed.value!==collapsed)globalToggle.props.onClick();const railToggle=find(mounted.root,el=>el.props.id==='work-taskrail-toggle');if(work.workTaskRailCollapsed.value!==railCollapsed)await railToggle.props.onClick({currentTarget:railToggle});await settle();assert.equal(globalToggle.props['aria-expanded'],!collapsed);assert.equal(railToggle.props['aria-expanded'],!railCollapsed);assert.equal(find(mounted.root,el=>el.props.id==='work-taskrail').style.display==='none',railCollapsed);assert.ok(railToggle.isConnected);assert.equal(JSON.stringify([h.chat.activeConversationId.value,h.chat.agentMode.value,h.chat.inputText.value,h.chat.modeMessageBuckets.value,h.plugins.paperSearchResults.value]),before);}}finally{mounted.close();h.scope.stop();}});
test('compiled query keeps selected plugin tags removable and source management reachable',async()=>{const h=hooks(),html=source('index.html');h.chat.agentMode.value='paper';h.plugins.activeInputPlugins.value=[{id:'chosen-source',name:'Chosen source',canSearchLive:true,searchSourceKey:'crossref'}];const view=await mount({template:slice(html,'<form class="work-paper-query"','</form>')+'</form>',setup(){return{agentMode:h.chat.agentMode,inputText:h.chat.inputText,isSearchingPapers:h.plugins.isSearchingPapers,thinkingAgent:h.chat.thinkingAgent,sendMessage(){},installedPlugins:h.plugins.installedPlugins,activeInputPlugins:h.plugins.activeInputPlugins,removeActiveInputPlugin:h.plugins.removeActiveInputPlugin,openPluginMarket:h.plugins.openPluginMarket};}});try{assert.match(textOf(view.root),/Chosen source/);find(view.root,el=>el.props['aria-label']==='移除标签 Chosen source').props.onClick();await settle();assert.equal(h.plugins.activeInputPlugins.value.length,0);button(view.root,'管理来源与插件').props.onClick();assert.equal(h.plugins.showPluginMarketModal.value,true);}finally{view.close();h.scope.stop();}});
test('compiled paper result and dialog tabs call the existing handler once and keep task draft and mode',async()=>{const h=hooks(),html=source('index.html'),header=html.indexOf('<header class="work-context-header"'),a=html.indexOf('<div v-if="agentMode === \'paper\'"',header),b=html.indexOf('<!-- 论文检索后吸顶',a),calls=[];assert.ok(a>header&&b>a);h.chat.agentMode.value='paper';h.chat.activeConversationId.value='same-paper-task';h.chat.inputText.value='unchanged draft';const mounted=await mount({template:html.slice(a,b),setup(){return{agentMode:h.chat.agentMode,paperActiveTab:h.chat.paperActiveTab,paperSearchResults:h.plugins.paperSearchResults,setPaperActiveTab:tab=>{calls.push(tab);h.chat.setPaperActiveTab(tab);}};}});try{for(const tab of ['dialog','results']){find(mounted.root,el=>el.props.id==='tab-paper-'+tab+'-btn').props.onClick();await settle();assert.equal(h.chat.paperActiveTab.value,tab);assert.equal(find(mounted.root,el=>el.props.id==='tab-paper-'+tab+'-btn').props['aria-pressed'],true);assert.equal(h.chat.activeConversationId.value,'same-paper-task');assert.equal(h.chat.inputText.value,'unchanged draft');assert.equal(h.chat.agentMode.value,'paper');}assert.deepEqual(calls,['dialog','results']);}finally{mounted.close();h.scope.stop();}});
test('installed query source controls select remove and re-add one source without changing the paper task',async()=>{
    const h=hooks(),html=source('index.html');
    localStorage.setItem('token','synthetic-source-owner'); h.user.value={username:'Alice'}; await settle();
    const {resolvePaperSourceKeys}=await import('../js/config/academicPlugins.js');
    const {ACADEMIC_PROVIDERS,clearAcademicCache}=await import('../js/api/academic/aggregate.js');
    const previous={crossref:ACADEMIC_PROVIDERS.crossref.search,openalex:ACADEMIC_PROVIDERS.openalex.search},searches=[];
    ACADEMIC_PROVIDERS.crossref.search=async query=>{searches.push(['crossref',query]);return[];};
    ACADEMIC_PROVIDERS.openalex.search=async query=>{searches.push(['openalex',query]);return[];};
    clearAcademicCache();h.chat.agentMode.value='paper';h.chat.activeConversationId.value='same-paper-task';h.chat.inputText.value='kept draft';h.plugins.installedPluginIds.value=['plugin_crossref','plugin_openalex'];h.plugins.activeInputPlugins.value=[];
    const mounted=await mount({template:slice(html,'<form class="work-paper-query"','</form>')+'</form>',setup(){return{agentMode:h.chat.agentMode,inputText:h.chat.inputText,isSearchingPapers:h.plugins.isSearchingPapers,thinkingAgent:h.chat.thinkingAgent,sendMessage:()=>h.plugins.executePaperSearch(h.chat.inputText.value),installedPlugins:h.plugins.installedPlugins,activeInputPlugins:h.plugins.activeInputPlugins,insertPluginToInput:h.plugins.insertPluginToInput,removeActiveInputPlugin:h.plugins.removeActiveInputPlugin,openPluginMarket:h.plugins.openPluginMarket};}});
    try{const before=JSON.stringify([h.chat.activeConversationId.value,h.chat.agentMode.value,h.chat.paperActiveTab.value,h.chat.inputText.value]);const crossrefControl=()=>find(mounted.root,el=>el.props['data-work-query-source']==='plugin_crossref');assert.ok(crossrefControl(),'Installed query must expose a native Crossref selector');assert.equal(walk(mounted.root).filter(el=>el.props['data-work-query-source']).length,2);assert.equal(crossrefControl().props['aria-pressed'],false);crossrefControl().props.onClick();await settle();assert.deepEqual(resolvePaperSourceKeys(null,h.plugins.activeInputPlugins.value,h.plugins.installedPlugins.value,capabilityFacts),['crossref']);assert.equal(crossrefControl().props['aria-pressed'],true);assert.equal(JSON.stringify([h.chat.activeConversationId.value,h.chat.agentMode.value,h.chat.paperActiveTab.value,h.chat.inputText.value]),before);await find(mounted.root,el=>el.tag==='form').props.onSubmit({preventDefault(){}});assert.deepEqual(searches,[['crossref','kept draft']]);assert.deepEqual(h.plugins.paperSourceStatuses.value.map(source=>source.key),['crossref']);find(mounted.root,el=>el.props['aria-label']==='移除标签 Crossref DOI Resolver').props.onClick();await settle();assert.equal(h.plugins.activeInputPlugins.value.length,0);crossrefControl().props.onClick();await settle();crossrefControl().props.onClick();await settle();assert.equal(h.plugins.activeInputPlugins.value.length,1);assert.deepEqual(resolvePaperSourceKeys(null,h.plugins.activeInputPlugins.value,h.plugins.installedPlugins.value,capabilityFacts),['crossref']);assert.equal(JSON.stringify([h.chat.activeConversationId.value,h.chat.agentMode.value,h.chat.paperActiveTab.value,h.chat.inputText.value]),before);assert.equal(h.plugins.showPluginMarketModal.value,false);assert.equal(h.plugins.activeSearchPlugin.value,null);}
    finally{ACADEMIC_PROVIDERS.crossref.search=previous.crossref;ACADEMIC_PROVIDERS.openalex.search=previous.openalex;clearAcademicCache();mounted.close();h.scope.stop();}
});
